/* Store Runner V193 — interface contrats expo cuisinistes Rhône-Alpes. */
(function(root){
'use strict';

const SHEET_ID='srCuisineSheet',CARD_ID='srCuisineContractCard';
let dialog=null,body=null,status=null,busy=false,quickObserver=null,visitObserver=null,renderQueued=false;
function C(){return root.StoreRunnerCuisineV193||null}
function db(){try{return root.__chefStorage||root.localStorage||null}catch(e){return null}}
function stores(){try{return Array.isArray(root.state&&root.state.stores)?root.state.stores:[]}catch(e){return[]}}
function el(tag,text,cls){const n=root.document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function btn(text,fn,cls){const b=el('button',text,cls||'secondary');b.type='button';b.addEventListener('click',fn);return b}
function eur(v){return v==null?'—':Math.round(Number(v)).toLocaleString('fr-FR')+' €'}
function pct(v){return v==null?'—':String(Math.round(Number(v)*10)/10).replace('.',',')+' %'}
function say(msg,error){if(status){status.textContent=msg||'';status.classList.toggle('bad',!!error)}}
function dispatch(){try{root.document.dispatchEvent(new CustomEvent('store-runner:cuisine-updated'))}catch(e){}}

function ensureStyle(){if(!root.document||root.document.getElementById('sr-cuisine-v193-style'))return;const s=el('style');s.id='sr-cuisine-v193-style';s.textContent=
  '#'+SHEET_ID+'{box-sizing:border-box;width:min(780px,calc(100vw - 18px));max-width:calc(100vw - 18px);max-height:calc(100dvh - 18px);overflow:auto;padding:16px;border:1px solid #dce2ea;border-radius:24px;background:#fff;color:#1d2939}'
  +'#'+SHEET_ID+'::backdrop{background:rgba(17,24,39,.45)}.srCuisineHead{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.srCuisineHead h2{margin:0;font-size:20px}.srCuisineHead p{margin:4px 0 0;font-size:11px;color:#667085}.srCuisineImports{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:12px 0}.srCuisineImports button{min-height:46px;border-radius:13px;border:1px solid #d8dee8;background:#fff;font-weight:800}.srCuisineStatus{min-height:18px;font-size:11px;color:#315b9d}.srCuisineStatus.bad{color:#b42318}.srCuisineRow{border:1px solid #e2e6ed;border-radius:15px;padding:11px;margin:9px 0;background:#fff}.srCuisineRow h3{margin:0;font-size:14px}.srCuisineBadges{display:flex;gap:6px;flex-wrap:wrap;margin:6px 0}.srCuisineBadge{display:inline-block;padding:3px 8px;border-radius:9px;font-size:10px;font-weight:850;background:#eef2ff;color:#334155}.srCuisineBadge.alert{background:#fdecea;color:#a3261c}.srCuisineBadge.active{background:#fff5e6;color:#8a5200}.srCuisineBadge.ok{background:#e9f7ef;color:#1a6b42}.srCuisineGrid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;margin-top:8px}.srCuisineCell{padding:7px;border:1px solid #e6e9ef;border-radius:11px;background:#fafbfc;min-width:0}.srCuisineCell span{display:block;font-size:9px;color:#667085}.srCuisineCell b{display:block;font-size:11.5px;margin-top:2px;overflow-wrap:anywhere}.srCuisineMeta{font-size:10.5px;color:#667085;line-height:1.45;margin:7px 0 0;white-space:pre-line}.srCuisineProducts{margin-top:8px;border-top:1px solid #edf0f4;padding-top:7px}.srCuisineProduct{font-size:10.5px;line-height:1.4;margin:4px 0}.srCuisineMap{width:100%;min-height:44px;margin-top:8px;border:1px solid #d5dbe5;border-radius:11px;background:#fff}.srCuisineEmpty{padding:18px;text-align:center;border:1px dashed #d7dde7;border-radius:14px;color:#667085;font-size:11px}'
  +'#'+CARD_ID+'{margin:10px 0;padding:11px;border:1px solid #e2e6ed;border-radius:15px;background:#fffaf3;font-size:11px;line-height:1.45}#'+CARD_ID+' h3{margin:0 0 7px;font-size:14px}#'+CARD_ID+' .srCuisineGrid{grid-template-columns:1fr 1fr}'
  +'.srCuisineBrief193{margin:10px 0 14px;padding:12px;border:1px solid #ecd9bd;border-radius:16px;background:#fffaf3;color:#1d2939}.srCuisineBrief193 h3{margin:0;font-size:13px}.srCuisineBrief193 .srCuisineGrid{grid-template-columns:1fr 1fr}.srCuisineBrief193 .srCuisineMeta{color:#5f5142}'
  +'@media(max-width:520px){.srCuisineImports{grid-template-columns:1fr}.srCuisineGrid{grid-template-columns:1fr 1fr}#'+SHEET_ID+'{padding:13px}.srCuisineRow{padding:10px}}';root.document.head.appendChild(s)}
function close(){if(dialog&&dialog.open)dialog.close()}
function open(){ensureDialog();render();if(!dialog.open)dialog.showModal()}
function ensureDialog(){if(dialog||!root.document)return dialog;ensureStyle();dialog=el('dialog');dialog.id=SHEET_ID;const head=el('div',undefined,'srCuisineHead'),copy=el('div');copy.append(el('h2','Contrats expo · Rhône-Alpes'),el('p','Suivi Schmidt / Cuisinella local. Seul le périmètre HITLIST Auvergne-Rhone-Alpes est conservé.'));head.append(copy,btn('Fermer',close));dialog.append(head);
  const imports=el('div',undefined,'srCuisineImports'),followInput=el('input'),tariffInput=el('input');followInput.type='file';followInput.accept='.xlsm,.xlsx';followInput.hidden=true;tariffInput.type='file';tariffInput.accept='.xlsx,.xlsm';tariffInput.hidden=true;
  imports.append(btn('Importer suivi contrats .xlsm',()=>!busy&&followInput.click()),btn('Importer tarifs / références .xlsx',()=>!busy&&tariffInput.click()));dialog.append(imports,followInput,tariffInput);status=el('div','Les fichiers restent sur cet appareil.','srCuisineStatus');body=el('div');dialog.append(status,body);root.document.body.append(dialog);
  followInput.addEventListener('change',()=>{const f=followInput.files&&followInput.files[0];if(f)importFollow(f);followInput.value=''});tariffInput.addEventListener('change',()=>{const f=tariffInput.files&&tariffInput.files[0];if(f)importTariff(f);tariffInput.value=''});return dialog}
async function importFollow(file){const api=C();if(!api)return;busy=true;say('Lecture du suivi contrats sur cet appareil…');const planBefore=JSON.stringify(root.state&&root.state.plan||{}),prioBefore=JSON.stringify((root.state&&root.state.stores||[]).map(s=>[s.id,s.priority]));try{const snap=await api.parseFollowUp(new Uint8Array(await file.arrayBuffer()),{fileName:file.name});api.saveSnapshot(db(),snap);const current=snap.stores.filter(s=>s.currentContract).length;say(snap.region+' importé · '+snap.stores.length+' cuisinistes · '+current+' contrat'+(current>1?'s':'')+' actif'+(current>1?'s':'')+'.');render();renderStoreCard();queueVisit();dispatch();if(planBefore!==JSON.stringify(root.state&&root.state.plan||{})||prioBefore!==JSON.stringify((root.state&&root.state.stores||[]).map(s=>[s.id,s.priority])))throw new Error('Protection : le planning ou les priorités structurelles ont changé pendant l’import.')}catch(e){say((e&&e.message)||'Import impossible.',true)}finally{busy=false}}
async function importTariff(file){const api=C();if(!api)return;busy=true;say('Lecture des tarifs / références sur cet appareil…');try{const snap=await api.parseTariff(new Uint8Array(await file.arrayBuffer()),{fileName:file.name});api.saveTariff(db(),snap);say('Tarifs importés · '+snap.products.length+' référence'+(snap.products.length>1?'s':'')+' exploitables.');render();renderStoreCard();queueVisit();dispatch()}catch(e){say((e&&e.message)||'Import tarifs impossible.',true)}finally{busy=false}}
function cell(grid,label,value){const c=el('div',undefined,'srCuisineCell');c.append(el('span',label),el('b',value));grid.append(c)}
function contractBlock(host,c){const grid=el('div',undefined,'srCuisineGrid');cell(grid,'Objectif',eur(c.objective));cell(grid,'Réalisé',eur(c.realized));cell(grid,'Progression',pct(c.progressPct));cell(grid,'Mois restant',String(c.monthsRemaining===''?'—':c.monthsRemaining));host.append(grid);const meta=[];if(c.start||c.end)meta.push('Période : '+(c.start||'—')+' → '+(c.end||'—'));if(c.closure)meta.push('Clôture source : '+c.closure);if(c.bill!=null)meta.push('À facturer : '+eur(c.bill));if(c.portfolio!=null)meta.push('Portefeuille mois : '+eur(c.portfolio));if(meta.length)host.append(el('p',meta.join('\n'),'srCuisineMeta'));const products=c.productsEnriched||[];if(products.length){const wrap=el('div',undefined,'srCuisineProducts');for(const p of products){const t=p.tariff,detail=t?[t.family,t.segment,t.description].filter(Boolean).join(' · '):'Référence non trouvée dans le tarif courant';wrap.append(el('div',p.ref+' · '+detail+(t&&t.storePrice!=null?' · '+eur(t.storePrice):'')+(t&&t.contractObjective12!=null?' · objectif x12 '+eur(t.contractObjective12):''),'srCuisineProduct'))}host.append(wrap)}}
function mappingSelect(r){const api=C(),select=el('select',undefined,'srCuisineMap');select.append(Object.assign(el('option','Rattacher à un magasin Store Runner…'),{value:''}));for(const s of stores().slice().sort((a,b)=>String(a.enseigne+' '+a.ville).localeCompare(String(b.enseigne+' '+b.ville),'fr'))){select.append(Object.assign(el('option',(s.enseigne||'Magasin')+' · '+(s.ville||'')),{value:String(s.id)}))}select.onchange=()=>{if(!select.value)return;api.rememberMatch(db(),r.key,select.value);say('Rattachement enregistré pour '+r.brand+' '+r.city+'.');render();renderStoreCard();dispatch()};return select}
function rowCard(r){const box=el('section',undefined,'srCuisineRow');box.append(el('h3',r.brand+' · '+r.city));const badges=el('div',undefined,'srCuisineBadges');if(r.currentContract){const alert=/alerte/i.test(r.currentContract.status||'');badges.append(el('span',r.currentContract.status||'Contrat actif','srCuisineBadge '+(alert?'alert':'active')))}else badges.append(el('span','Aucun contrat actif','srCuisineBadge'));if(r.storeId)badges.append(el('span','Rattaché Store Runner','srCuisineBadge ok'));else badges.append(el('span','Non rattaché','srCuisineBadge'));box.append(badges);if(r.currentContract)contractBlock(box,r.currentContract);else if(r.lastContract){box.append(el('p','Dernier contrat : '+(r.lastContract.status||'historique')+' · fin '+(r.lastContract.end||'—')+' · progression '+pct(r.lastContract.progressPct)+(r.lastContract.closure?' · clôture '+r.lastContract.closure:''),'srCuisineMeta'))}else box.append(el('p','Aucun contrat actif ou historique retrouvé dans le suivi importé.','srCuisineMeta'));if(r.urgency&&r.urgency.reasons&&r.urgency.reasons.length)box.append(el('p','Signal Contrat expo : '+r.urgency.reasons.join(' · '),'srCuisineMeta'));if(!r.storeId)box.append(mappingSelect(r));return box}
function render(){if(!body||!C())return;body.replaceChildren();const board=C().dashboard(db(),stores());if(!board.rows.length){body.append(el('div','Aucun suivi cuisiniste importé. Importe le .xlsm reçu pour démarrer.','srCuisineEmpty'));return}const meta=el('p','Périmètre : '+board.region+' · '+board.rows.length+' cuisinistes'+(board.tariffImportedAt?' · tarifs chargés':' · tarifs non chargés'),'srCuisineMeta');body.append(meta);for(const r of board.rows)body.append(rowCard(r))}
function currentStoreId(){const b=root.document&&root.document.getElementById('srQuickStart');return String(b&&b.dataset&&b.dataset.srStart||'')}
function renderStoreCard(){if(!root.document||!C())return false;const sheet=root.document.getElementById('storeQuickSheet');if(!sheet||!sheet.classList.contains('open'))return false;const id=currentStoreId(),old=root.document.getElementById(CARD_ID);if(!id){if(old)old.remove();return false}const r=C().rowForStore(db(),id,stores());if(!r){if(old)old.remove();return false}ensureStyle();const card=old||el('section');card.id=CARD_ID;card.replaceChildren();card.append(el('h3','📋 Contrat Expo'));const badges=el('div',undefined,'srCuisineBadges');badges.append(el('span',r.currentContract?(r.currentContract.status||'Contrat actif'):'Aucun contrat actif','srCuisineBadge '+(r.currentContract&&/alerte/i.test(r.currentContract.status||'')?'alert':'')));card.append(badges);if(r.currentContract)contractBlock(card,r.currentContract);else if(r.lastContract)card.append(el('p','Dernier contrat : fin '+(r.lastContract.end||'—')+' · '+pct(r.lastContract.progressPct)+(r.lastContract.closure?' · clôture '+r.lastContract.closure:''),'srCuisineMeta'));else card.append(el('p','Aucun contrat retrouvé dans le dernier import.','srCuisineMeta'));if(!old){const anchor=root.document.getElementById('srStoreMemory')||sheet.querySelector('.sheetBottom');if(anchor)sheet.insertBefore(card,anchor);else sheet.append(card)}return true}
function activeVisitStoreId(){try{const id=root.StoreRunnerVisits&&root.StoreRunnerVisits.activeVisitId&&root.StoreRunnerVisits.activeVisitId();if(!id)return'';const v=((root.state&&root.state.businessV2&&root.state.businessV2.visits)||[]).find(x=>String(x.id)===String(id));return v?String(v.storeId):''}catch(e){return''}}
function createVisitBrief(r){const box=el('section',undefined,'srCuisineBrief193');box.dataset.storeId=String(r.storeId);box.append(el('h3','📋 Brief Contrat Expo · '+r.brand+' '+r.city));const badges=el('div',undefined,'srCuisineBadges');badges.append(el('span',r.currentContract?(r.currentContract.status||'Contrat actif'):'Aucun contrat actif','srCuisineBadge '+(r.currentContract&&/alerte/i.test(r.currentContract.status||'')?'alert':'active')));box.append(badges);if(r.currentContract){const g=el('div',undefined,'srCuisineGrid');cell(g,'Progression',pct(r.currentContract.progressPct));cell(g,'Objectif',eur(r.currentContract.objective));cell(g,'Réalisé',eur(r.currentContract.realized));cell(g,'Temps restant',String(r.currentContract.monthsRemaining===''?'—':r.currentContract.monthsRemaining)+' mois');box.append(g);const refs=(r.currentContract.productsEnriched||[]).map(p=>p.ref).filter(Boolean);if(refs.length)box.append(el('p','Produits expo : '+refs.join(' · '),'srCuisineMeta'));if(r.urgency&&r.urgency.reasons.length)box.append(el('p','À surveiller : '+r.urgency.reasons.join(' · '),'srCuisineMeta'))}else if(r.lastContract)box.append(el('p','Aucun contrat actif. Dernier contrat terminé '+(r.lastContract.end||'—')+' · '+pct(r.lastContract.progressPct)+'.','srCuisineMeta'));else box.append(el('p','Aucun contrat actif trouvé : situation à qualifier en magasin.','srCuisineMeta'));return box}
function renderVisitBrief(){if(!root.document||!C())return false;const d=root.document.getElementById('srVisitDialog');if(!d||!d.open)return false;const intro=d.querySelector('.sr-terrainIntro'),id=activeVisitStoreId();if(!intro||!id)return false;const r=C().rowForStore(db(),id,stores()),old=d.querySelector('.srCuisineBrief193');if(!r){if(old)old.remove();return false}if(old&&old.dataset.storeId===String(id))return true;if(old)old.remove();intro.parentNode.insertBefore(createVisitBrief(r),intro);return true}
function queueVisit(){if(renderQueued)return;renderQueued=true;const run=()=>{renderQueued=false;renderVisitBrief()};if(root.requestAnimationFrame)root.requestAnimationFrame(run);else setTimeout(run,0)}
function ensureMenu(){if(!root.document)return false;const grid=root.document.querySelector('#moreSheetV2 .moreSheetGrid');if(!grid||grid.querySelector('[data-cuisine-v193]'))return false;const b=el('button','▦ Contrats expo');b.type='button';b.dataset.cuisineV193='1';grid.append(b);return true}
function installObservers(){if(!root.document)return;if(!quickObserver){const sheet=root.document.getElementById('storeQuickSheet');if(sheet){quickObserver=new MutationObserver(()=>setTimeout(renderStoreCard,0));quickObserver.observe(sheet,{attributes:true,subtree:true,attributeFilter:['class','aria-hidden','data-sr-start']})}}if(!visitObserver){const d=root.document.getElementById('srVisitDialog');if(d){visitObserver=new MutationObserver(queueVisit);visitObserver.observe(d,{attributes:true,subtree:true,childList:true,attributeFilter:['open']})}}}
function install(){ensureStyle();ensureDialog();ensureMenu();installObservers();renderStoreCard();queueVisit()}
function schedule(){setTimeout(install,0);setTimeout(install,300);setTimeout(install,1000)}
root.StoreRunnerCuisineUIV193={open,render,renderStoreCard,renderVisitBrief,install};
if(root.document){root.document.addEventListener('click',e=>{const b=e.target&&e.target.closest&&e.target.closest('[data-cuisine-v193]');if(b){e.preventDefault();open()}},true);root.document.addEventListener('store-runner:home-rendered',schedule);root.document.addEventListener('store-runner:data-restored',schedule);root.document.addEventListener('store-runner:cuisine-updated',()=>{renderStoreCard();queueVisit()});if(root.document.readyState==='loading')root.document.addEventListener('DOMContentLoaded',schedule,{once:true});else schedule()}
})(typeof window!=='undefined'?window:globalThis);
