/* Mode national : catalogue commun + secteurs configurables, sans inventer le découpage Samsung. */
(function(root){
'use strict';
const PROFILE_KEY='chef-national-sector-profile-v1';
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function deptFromZip(zip){zip=String(zip||'').trim();if(/^97\d/.test(zip))return zip.slice(0,3);if(/^20/.test(zip))return'20';return /^\d{2}/.test(zip)?zip.slice(0,2):''}
function localProfile(){try{return JSON.parse((window.__chefStorage||localStorage).getItem(PROFILE_KEY)||'null')}catch(e){return null}}
function saveProfile(p){try{(window.__chefStorage||localStorage).setItem(PROFILE_KEY,JSON.stringify(p))}catch(e){}}
function normalizeOfficial(s){return {id:String(s.id||('national-'+Math.random().toString(36).slice(2))),enseigne:s.enseigne||'',sourceName:s.sourceName||((s.enseigne||'Magasin')+' '+(s.ville||'')),adresse:s.adresse||'',codePostal:s.codePostal||'',ville:s.ville||'',dept:s.dept||deptFromZip(s.codePostal),lat:s.lat==null?null:Number(s.lat),lon:s.lon==null?null:Number(s.lon),region:s.region||'',regionCode:s.regionCode||'',freq:s.freq||'Mensuel',intervalDays:Number(s.intervalDays||30),priority:Number(s.priority||3),active:true,products:Array.isArray(s.products)&&s.products.length?s.products:['À confirmer'],source:s.source||'Catalogue national',sourceUrl:s.sourceUrl||'',nationalCatalog:true}}
function normalizeBoulanger(s){return normalizeOfficial({id:'national-boulanger-'+s.id,enseigne:'Boulanger',sourceName:s.name,adresse:s.address,codePostal:s.zip,ville:s.city,dept:deptFromZip(s.zip),lat:s.lat,lon:s.lng,source:'Catalogue Boulanger fourni',sourceUrl:'',products:['À confirmer']})}
function duplicate(a,b){return a.id===b.id||(norm(a.enseigne)===norm(b.enseigne)&&norm(a.ville)===norm(b.ville)&&norm(a.adresse)===norm(b.adresse))}
async function loadCatalog(){let official=[];try{const r=await fetch('./data/official-stores.json?national='+Date.now(),{cache:'no-store'});if(r.ok){const d=await r.json();official=Array.isArray(d.stores)?d.stores.map(normalizeOfficial):[]}}catch(e){}
 const boul=(root.BOULANGER_NATIONAL_STORES||[]).map(normalizeBoulanger);const out=[];official.concat(boul).forEach(s=>{if(!out.some(x=>duplicate(x,s)))out.push(s)});return out}
function regionForDept(dept){const map={
'01':'Auvergne-Rhône-Alpes','03':'Auvergne-Rhône-Alpes','07':'Auvergne-Rhône-Alpes','15':'Auvergne-Rhône-Alpes','26':'Auvergne-Rhône-Alpes','38':'Auvergne-Rhône-Alpes','42':'Auvergne-Rhône-Alpes','43':'Auvergne-Rhône-Alpes','63':'Auvergne-Rhône-Alpes','69':'Auvergne-Rhône-Alpes','73':'Auvergne-Rhône-Alpes','74':'Auvergne-Rhône-Alpes',
'21':'Bourgogne-Franche-Comté','25':'Bourgogne-Franche-Comté','39':'Bourgogne-Franche-Comté','58':'Bourgogne-Franche-Comté','70':'Bourgogne-Franche-Comté','71':'Bourgogne-Franche-Comté','89':'Bourgogne-Franche-Comté','90':'Bourgogne-Franche-Comté',
'59':'Hauts-de-France','62':'Hauts-de-France','75':'Île-de-France','77':'Île-de-France','78':'Île-de-France','91':'Île-de-France','92':'Île-de-France','93':'Île-de-France','94':'Île-de-France','95':'Île-de-France','13':"Provence-Alpes-Côte d'Azur",'06':"Provence-Alpes-Côte d'Azur",'31':'Occitanie','34':'Occitanie','33':'Nouvelle-Aquitaine','44':'Pays de la Loire','67':'Grand Est'};return map[String(dept||'')]||''}
function enrichRegions(rows){rows.forEach(s=>{if(!s.dept)s.dept=deptFromZip(s.codePostal);if(!s.region)s.region=regionForDept(s.dept)});return rows}
function applySector(profile,rows){
 if(!root.state||!root.ChefReliability)throw Error('Application pas encore prête.');
 const selected=rows.filter(s=>(!profile.region||s.region===profile.region)&&(!profile.departments.length||profile.departments.includes(String(s.dept||''))));
 if(!selected.length)throw Error('Aucun magasin disponible dans ce secteur avec le catalogue actuel.');
 const R=root.ChefReliability,bundle=R.capture();
 const old=bundle.state.stores||[],visits=bundle.state.visits||{},notes=bundle.state.notes||{};
 const preservedById=new Map(old.map(s=>[String(s.id),s]));
 bundle.state.stores=selected.map(s=>{const oldRow=preservedById.get(String(s.id));return oldRow?Object.assign({},s,{freq:oldRow.freq||s.freq,intervalDays:oldRow.intervalDays||s.intervalDays,priority:oldRow.priority||s.priority,active:oldRow.active!==false,products:oldRow.products||s.products}):s});
 bundle.state.profile=bundle.state.profile||{};bundle.state.profile.sectorName=profile.name;bundle.state.profile.nationalSector={name:profile.name,region:profile.region,departments:profile.departments.slice()};
 bundle.state.plan={};bundle.state.visits=visits;bundle.state.notes=notes;
 R.checkpoint('Avant activation du secteur '+profile.name);R.persist(bundle);root.state=bundle.state;saveProfile(profile);
 if(typeof root.initControls==='function')root.initControls();if(typeof root.renderAll==='function')root.renderAll();if(typeof root.renderHeader==='function')root.renderHeader();return selected.length
}
function install(){
 const host=document.querySelector('#storesPanel .toolbar');if(!host||document.getElementById('nationalSectorBtn'))return;
 const btn=document.createElement('button');btn.id='nationalSectorBtn';btn.type='button';btn.className='secondary';btn.textContent='🌍 Secteur national';host.append(btn);
 const d=document.createElement('dialog');d.className='catalogDialog';d.innerHTML='<div class="catalogHead"><div><small>MODE MULTI-CHEFS DE SECTEUR</small><h2>Secteur national</h2></div><button class="catalogClose" type="button">✕</button></div><div class="catalogBody"><div class="notice">Le moteur national est prêt, mais le découpage officiel n’est pas encore connu. Tu peux déjà créer un secteur géographique par région/départements. Quand tu auras les 63 magasins exacts, on remplacera simplement l’affectation, sans refaire l’application.</div><div class="catalogForm open"><label>Nom du secteur<input id="nsName" placeholder="Ex. Rhône-Alpes Ouest"></label><label>Région<select id="nsRegion"><option value="">Toutes les régions disponibles</option></select></label><div><b>Départements</b><div id="nsDepartments" class="chips" style="margin-top:8px"></div></div><div id="nsPreview" class="catalogStats"></div><div class="catalogActions"><button type="button" class="primary" id="nsApply">Activer ce secteur</button></div><div class="catalogNote">L’activation remplace la liste visible des magasins par ceux du secteur choisi. Une sauvegarde automatique est créée avant le changement. Les historiques existants sont conservés quand les identifiants correspondent.</div></div></div>';document.body.append(d);
 const q=s=>d.querySelector(s),region=q('#nsRegion'),deps=q('#nsDepartments'),preview=q('#nsPreview'),name=q('#nsName');let rows=[];
 function selectedDepartments(){return [...deps.querySelectorAll('input:checked')].map(x=>x.value)}
 function renderDepartments(){const r=region.value;const list=[...new Set(rows.filter(s=>!r||s.region===r).map(s=>String(s.dept||'')).filter(Boolean))].sort();deps.innerHTML=list.map(x=>'<label class="chip"><input type="checkbox" value="'+esc(x)+'"> '+esc(x)+'</label>').join('');deps.querySelectorAll('input').forEach(x=>x.onchange=updatePreview);updatePreview()}
 function updatePreview(){const r=region.value,ds=selectedDepartments();const filtered=rows.filter(s=>(!r||s.region===r)&&(!ds.length||ds.includes(String(s.dept||''))));const counts={};filtered.forEach(s=>counts[s.enseigne]=(counts[s.enseigne]||0)+1);preview.textContent=filtered.length+' magasin(s) disponibles'+(Object.keys(counts).length?' · '+Object.entries(counts).map(([k,v])=>k+' '+v).join(' · '):'')}
 async function open(){d.showModal();preview.textContent='Chargement du catalogue national…';rows=enrichRegions(await loadCatalog());const regions=[...new Set(rows.map(s=>s.region).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr'));region.innerHTML='<option value="">Toutes les régions disponibles</option>'+regions.map(r=>'<option>'+esc(r)+'</option>').join('');const saved=localProfile()||(state.profile&&state.profile.nationalSector)||null;if(saved){name.value=saved.name||'';region.value=saved.region||''}renderDepartments();if(saved&&Array.isArray(saved.departments))deps.querySelectorAll('input').forEach(x=>x.checked=saved.departments.includes(x.value));updatePreview()}
 btn.onclick=open;q('.catalogClose').onclick=()=>d.close();region.onchange=renderDepartments;q('#nsApply').onclick=()=>{try{const profile={name:name.value.trim()||region.value||'Mon secteur',region:region.value,departments:selectedDepartments()};if(!confirm('Activer « '+profile.name+' » et charger uniquement les magasins correspondants ? Une sauvegarde sera créée avant le changement.'))return;const n=applySector(profile,rows);preview.textContent=n+' magasins chargés dans le secteur « '+profile.name+' ».';setTimeout(()=>d.close(),700)}catch(e){preview.textContent='Activation impossible : '+e.message}};
}
root.ChefNationalSectors={loadCatalog,applySector};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})(typeof window!=='undefined'?window:globalThis);
