/* Region discovery: explicit searches only; no existing sector data is sent. */
(function(root){
'use strict';
const BRANDS=['Boulanger','Darty','Fnac','Conforama','Cuisinella','Carrefour'];
const normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const coords=s=>typeof s.lat==='number'&&typeof s.lon==='number'&&Number.isFinite(s.lat)&&Number.isFinite(s.lon)&&Math.abs(s.lat)<=90&&Math.abs(s.lon)<=180;
function duplicate(a,list){return list.some(b=>a.id===b.id||(normalize(a.enseigne)===normalize(b.enseigne)&&((coords(a)&&coords(b)&&Math.hypot((a.lat-b.lat)*111320,(a.lon-b.lon)*111320*Math.cos(a.lat*Math.PI/180))<180)||(a.adresse&&b.adresse&&normalize(a.adresse)===normalize(b.adresse)&&a.ville&&normalize(a.ville)===normalize(b.ville)))))}
function query(region,brands){if(!/^\d{2}$/.test(region.code)||!brands.length||brands.some(b=>!BRANDS.includes(b)))throw Error('Choisis une région et au moins une enseigne.');const pattern='^('+brands.join('|')+')([ ;_-]|$)';return '[out:json][timeout:35];area["boundary"="administrative"]["admin_level"="4"]["ref:INSEE"="'+region.code+'"]->.r;.r out ids;(nwr(area.r)["shop"]["brand"~"'+pattern+'",i];nwr(area.r)["shop"]["name"~"'+pattern+'",i];);out center tags;'}
function parse(data,region,brands){if(!data||!Array.isArray(data.elements)||data.remark)throw Error('Réponse de recherche incomplète. Réessaie plus tard.');if(!data.elements.some(e=>e.type==='area'))throw Error('Contour de cette région indisponible dans la source.');const rows=[];for(const e of data.elements){const t=e.tags||{},brand=brands.find(b=>[t.brand,t.name].some(v=>new RegExp('^'+b+'(?:[ ;_-]|$)','i').test(v||'')));if(!brand||!['node','way','relation'].includes(e.type)||!Number.isSafeInteger(e.id)||!t.shop||['no','vacant','disused'].includes(t.shop)||t.disused==='yes'||t.abandoned==='yes')continue;const s={id:'osm-'+e.type+'-'+e.id,enseigne:brand,ville:t['addr:city']||t['addr:town']||t['addr:village']||'',adresse:t['addr:full']||[t['addr:housenumber'],t['addr:street']||t['addr:place']].filter(Boolean).join(' '),codePostal:t['addr:postcode']||'',dept:'',lat:e.lat??e.center?.lat,lon:e.lon??e.center?.lon,freq:'Mensuel',intervalDays:30,priority:3,active:true,products:['À confirmer'],region:region.nom,regionCode:region.code,source:'OpenStreetMap',sourceUrl:'https://www.openstreetmap.org/'+e.type+'/'+e.id,sourceFetchedAt:new Date().toISOString(),sourceName:t.name||brand};s.needsGeo=!coords(s);if(!duplicate(s,rows))rows.push(s)}return rows.sort((a,b)=>(a.enseigne+a.ville).localeCompare(b.enseigne+b.ville,'fr'))}
function commit(selected){const R=root.ChefReliability;if(!R)throw Error('Sauvegardes indisponibles : ajout interrompu.');const bundle=R.capture(),added=[];for(const s of selected){if(!coords(s)||!s.ville.trim())throw Error('Complète la ville et les coordonnées avant ajout.');if(!duplicate(s,bundle.state.stores)){const row=JSON.parse(JSON.stringify(s));bundle.state.stores.push(row);added.push(row)}}if(!added.length)return 0;R.validate(bundle);R.checkpoint('Avant ajout de '+added.length+' magasins');R.persist(bundle);root.state=bundle.state;return added.length}
const api={BRANDS,normalize,coords,duplicate,query,parse,commit};if(typeof module!=='undefined')module.exports=api;root.RegionStores=api;if(!root.document)return;
let controller=null,rows=[],cache=new Map(),cooldown=0;
async function json(url,options={}){const c=controller,t=setTimeout(()=>c.abort(),45000);try{const r=await fetch(url,{...options,signal:c.signal});if(r.status===429){cooldown=Date.now()+30000;throw Error('Service occupé. Patiente 30 secondes avant de réessayer.')}if(!r.ok)throw Error('Service indisponible ('+r.status+'). Réessaie plus tard.');return await r.json()}finally{clearTimeout(t)}}
function el(tag,text,cls){const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n}
function install(){const host=document.querySelector('#storesPanel .toolbar');if(!host||document.getElementById('regionDiscover'))return;const launch=el('button','＋ Ajouter une région','secondary');launch.id='regionDiscover';launch.type='button';host.append(launch);
const d=el('dialog',null,'regionDialog');d.innerHTML='<div class="regionHeading"><div><small>ÉTENDRE MON SECTEUR</small><h2>Ajouter une région</h2></div><button type="button" aria-label="Fermer">✕</button></div><p>Recherche les enseignes d’une région, puis choisis les magasins à ajouter.</p><label>Région<select id="regionChoice"><option value="">Charger les régions…</option></select></label><fieldset><legend>Enseignes recherchées</legend><div class="regionBrands"></div></fieldset><div class="regionActions"><button type="button" class="primary" id="regionSearch">Rechercher les magasins</button><button type="button" class="secondary" id="regionCancel" hidden>Annuler la recherche</button></div><p class="regionStatus" role="status" aria-live="polite"></p><p class="regionSource">Données © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">OpenStreetMap</a> · liste non exhaustive. Vérifie les adresses et l’activité des magasins ; la vente de produits Samsung n’est pas confirmée.</p><div class="regionResults"></div><div class="regionFooter"><span id="regionSelected">Aucun magasin sélectionné</span><button type="button" class="primary" id="regionImport" disabled>Ajouter la sélection</button></div>';
document.body.append(d);const select=d.querySelector('select'),search=d.querySelector('#regionSearch'),cancel=d.querySelector('#regionCancel'),status=d.querySelector('.regionStatus'),results=d.querySelector('.regionResults'),importBtn=d.querySelector('#regionImport');let regions=[],searching=false;
BRANDS.forEach(b=>{const l=el('label'),c=el('input');c.type='checkbox';c.value=b;c.checked=b!=='Carrefour';l.append(c,document.createTextNode(b));d.querySelector('.regionBrands').append(l)});
function message(t){status.textContent=t}function stop(){if(controller)controller.abort()}function close(){stop();d.close()}d.querySelector('.regionHeading button').onclick=close;d.addEventListener('cancel',stop);cancel.onclick=stop;
function selectedRows(){return [...results.querySelectorAll('input[data-select]:checked')].map(n=>rows[Number(n.dataset.select)])}
function count(){const n=selectedRows().length;d.querySelector('#regionSelected').textContent=n+' magasin'+(n>1?'s':'')+' sélectionné'+(n>1?'s':'');importBtn.disabled=!n||searching}
function clear(){rows=[];results.replaceChildren();count()}select.onchange=clear;d.querySelector('.regionBrands').onchange=clear;
function render(){results.replaceChildren();rows.forEach((s,i)=>{const card=el('article',null,'regionResult'),check=el('input');check.type='checkbox';check.dataset.select=i;const exists=duplicate(s,root.state.stores);check.disabled=exists||!coords(s)||!s.ville;check.setAttribute('aria-label','Sélectionner '+s.sourceName);check.onchange=count;const title=el('label',null,'regionResultTitle');title.append(check,document.createTextNode(s.sourceName));card.append(title);const addressLabel=el('label','Adresse'),address=el('input');address.value=s.adresse;address.placeholder='Adresse absente : à compléter si tu la connais';address.disabled=exists;address.oninput=()=>{s.adresse=address.value.trim()};addressLabel.append(address);card.append(addressLabel);const cityLabel=el('label','Ville'),city=el('input');city.value=s.ville;city.placeholder='Ville à compléter avant ajout';city.disabled=exists;city.oninput=()=>{s.ville=city.value.trim();check.disabled=exists||!coords(s)||!s.ville;if(check.disabled)check.checked=false;count()};cityLabel.append(city);card.append(cityLabel);const a=el('a','Voir la fiche et la position ↗');a.href=s.sourceUrl;a.target='_blank';a.rel='noopener noreferrer';card.append(a,el('small',exists?'Déjà présent ou doublon probable · non ajouté':!coords(s)?'Coordonnées absentes · ajout indisponible':!s.adresse?'Adresse à vérifier avant ta visite':s.codePostal||'Position disponible'));results.append(card)});count()}
launch.onclick=async()=>{d.showModal();if(regions.length||searching)return;controller=new AbortController();search.disabled=true;message('Chargement des régions…');try{const data=await json('https://geo.api.gouv.fr/regions');if(!Array.isArray(data)||!data.length)throw Error('Liste des régions indisponible.');regions=data.filter(r=>/^\d{2}$/.test(r.code)&&typeof r.nom==='string').sort((a,b)=>a.nom.localeCompare(b.nom,'fr'));select.replaceChildren(...regions.map(r=>{const o=el('option',r.nom);o.value=r.code;return o}));select.value=regions.some(r=>r.code==='84')?'84':regions[0].code;message('Choisis les enseignes puis lance la recherche.')}catch(e){message(e.name==='AbortError'?'Chargement annulé. Ferme et rouvre cette fenêtre pour réessayer.':e.message)}finally{search.disabled=false}};
search.onclick=async()=>{if(searching)return;if(Date.now()<cooldown){message('Patiente 30 secondes avant une nouvelle recherche.');return}const region=regions.find(r=>r.code===select.value),brands=[...d.querySelectorAll('.regionBrands input:checked')].map(c=>c.value);if(!region||!brands.length){message('Choisis une région et au moins une enseigne.');return}if(navigator.onLine===false){message('Cette recherche nécessite une connexion Internet.');return}clear();searching=true;search.disabled=true;select.disabled=true;d.querySelector('fieldset').disabled=true;cancel.hidden=false;controller=new AbortController();message('Recherche en cours… cela peut prendre une quarantaine de secondes.');try{const key=region.code+brands.join('|'),hit=cache.get(key);if(hit&&Date.now()-hit.time<900000)rows=JSON.parse(JSON.stringify(hit.rows));else{const data=await json('https://overpass.private.coffee/api/interpreter',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'data='+encodeURIComponent(query(region,brands))});rows=parse(data,region,brands);cache.set(key,{time:Date.now(),rows:JSON.parse(JSON.stringify(rows))})}render();message(rows.length?rows.length+' résultats. Coche les magasins à ajouter ; complète la ville si elle manque.':'Aucun résultat dans cette source pour cette sélection. Cela ne signifie pas qu’aucun magasin existe.')}catch(e){message(e.name==='AbortError'?'Recherche annulée ou délai dépassé. Tu peux réessayer.':e instanceof TypeError?'Connexion au service de recherche impossible. Vérifie Internet et réessaie plus tard.':e.message)}finally{searching=false;search.disabled=false;select.disabled=false;d.querySelector('fieldset').disabled=false;cancel.hidden=true;count()}};
importBtn.onclick=()=>{importBtn.disabled=true;try{const n=commit(selectedRows());if(typeof root.renderFilterControls==='function')root.renderFilterControls();root.renderAll();render();message(n+' magasin'+(n>1?'s':'')+' ajouté'+(n>1?'s':'')+' à ton secteur. Une sauvegarde a été conservée. Ils seront disponibles pour tes prochains plannings.')}catch(e){message('Ajout interrompu : '+e.message)}finally{count()}};
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})(typeof window!=='undefined'?window:globalThis);
