/* Region discovery: official brand directories first, OpenStreetMap only as complement. */
(function(root){
'use strict';
const BRANDS=['Boulanger','Darty','Fnac','Conforama','Cuisinella','Carrefour'];
const OFFICIAL_URLS={
 Boulanger:'https://www.boulanger.com/info/magasins/france',
 Darty:'https://magasin.darty.com/fr',
 Fnac:'https://www.fnac.com/localiser-magasin-fnac/w-4',
 Conforama:'https://www.conforama.fr/magasins-conforama',
 Cuisinella:'https://www.ma.cuisinella/fr-fr/liste-magasins',
 Carrefour:'https://www.carrefour.fr/magasin'
};
const CATEGORIES={Boulanger:['electronics','appliance','hifi'],Darty:['electronics','appliance','kitchen'],Fnac:['electronics','books','department_store'],Conforama:['furniture','department_store'],Cuisinella:['kitchen','furniture'],Carrefour:['supermarket','department_store']};
const normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const coords=s=>typeof s.lat==='number'&&typeof s.lon==='number'&&Number.isFinite(s.lat)&&Number.isFinite(s.lon)&&Math.abs(s.lat)<=90&&Math.abs(s.lon)<=180;
function duplicate(a,list){return list.some(b=>a.id===b.id||(normalize(a.enseigne)===normalize(b.enseigne)&&((coords(a)&&coords(b)&&Math.hypot((a.lat-b.lat)*111320,(a.lon-b.lon)*111320*Math.cos((a.lat||0)*Math.PI/180))<180)||(a.adresse&&b.adresse&&normalize(a.adresse)===normalize(b.adresse)&&a.ville&&normalize(a.ville)===normalize(b.ville)))))}
function complete(s){return coords(s)&&typeof s.ville==='string'&&!!s.ville.trim()&&typeof s.adresse==='string'&&!!s.adresse.trim()}
function matchBrand(t,brands){return brands.find(b=>CATEGORIES[b].includes(t.shop)&&(!t.brand||normalize(t.brand)===normalize(b))&&[t.brand,t.name].some(v=>normalize(v)===normalize(b)||(!t.brand&&new RegExp('^'+b+'(?:[ _-]|$)','i').test(v||'')))&&!/boulangerie|patissi|pâtissi|artisan|pain|bakery/i.test(t.name||''))}
function query(region,brands){if(!/^\d{2}$/.test(region.code)||!brands.length||brands.some(b=>!BRANDS.includes(b)))throw Error('Choisis une région et au moins une enseigne.');const selectors=brands.map(b=>{const category='["shop"~"^('+CATEGORIES[b].join('|')+')$",i]';return 'nwr(area.r)'+category+'["brand"~"^'+b+'$",i];nwr(area.r)'+category+'["name"~"^'+b+'([ _-]|$)",i];'}).join('');return '[out:json][timeout:35];area["boundary"="administrative"]["admin_level"="4"]["ref:INSEE"="'+region.code+'"]->.r;.r out ids;('+selectors+');out center tags;'}
function parseOSM(data,region,brands){if(!data||!Array.isArray(data.elements)||data.remark)throw Error('Réponse OpenStreetMap incomplète. Réessaie plus tard.');const rows=[];for(const e of data.elements){const t=e.tags||{},brand=matchBrand(t,brands);if(!brand||!['node','way','relation'].includes(e.type)||!Number.isSafeInteger(e.id)||!t.shop||['no','vacant','disused'].includes(t.shop)||t.disused==='yes'||t.abandoned==='yes')continue;const s={id:'osm-'+e.type+'-'+e.id,enseigne:brand,ville:t['addr:city']||t['addr:town']||t['addr:village']||'',adresse:t['addr:full']||[t['addr:housenumber'],t['addr:street']||t['addr:place']].filter(Boolean).join(' '),codePostal:t['addr:postcode']||'',dept:'',lat:e.lat??e.center?.lat,lon:e.lon??e.center?.lon,freq:'Mensuel',intervalDays:30,priority:3,active:true,products:['À confirmer'],region:region.nom,regionCode:region.code,source:'OpenStreetMap (complément)',sourceUrl:'https://www.openstreetmap.org/'+e.type+'/'+e.id,sourceFetchedAt:new Date().toISOString(),sourceName:t.name||brand};s.needsGeo=!coords(s);if(!duplicate(s,rows))rows.push(s)}return rows}
function normalizeOfficial(x){const s=JSON.parse(JSON.stringify(x||{}));s.id=s.id||('official-'+normalize((s.enseigne||'magasin')+'-'+(s.codePostal||'')+'-'+(s.sourceName||s.ville||'')));s.freq=s.freq||'Mensuel';s.intervalDays=Number(s.intervalDays||30);s.priority=Number(s.priority||3);s.active=s.active!==false;s.products=Array.isArray(s.products)&&s.products.length?s.products:['À confirmer'];s.source=s.source||('Annuaire officiel '+(s.enseigne||''));s.sourceUrl=s.sourceUrl||OFFICIAL_URLS[s.enseigne]||'';s.sourceName=s.sourceName||((s.enseigne||'Magasin')+' '+(s.ville||''));s.lat=s.lat==null?null:Number(s.lat);s.lon=s.lon==null?null:Number(s.lon);return s}
function commit(selected){const R=root.ChefReliability;if(!R)throw Error('Sauvegardes indisponibles : ajout interrompu.');const bundle=R.capture(),added=[];for(const s of selected){if(!complete(s))throw Error('Adresse, ville et coordonnées obligatoires avant ajout.');if(!duplicate(s,bundle.state.stores)){const row=JSON.parse(JSON.stringify(s));bundle.state.stores.push(row);added.push(row)}}if(!added.length)return 0;R.validate(bundle);R.checkpoint('Avant ajout de '+added.length+' magasins');R.persist(bundle);root.state=bundle.state;return added.length}
const api={BRANDS,OFFICIAL_URLS,normalize,coords,complete,matchBrand,duplicate,query,parseOSM,commit};if(typeof module!=='undefined')module.exports=api;root.RegionStores=api;if(!root.document)return;
let controller=null,rows=[],regions=[],officialSnapshot=null,cooldown=0;
async function json(url,options={}){const c=controller,t=setTimeout(()=>c&&c.abort(),45000);try{const r=await fetch(url,{...options,signal:c?c.signal:undefined});if(r.status===429){cooldown=Date.now()+30000;throw Error('Service occupé. Patiente 30 secondes avant de réessayer.')}if(!r.ok)throw Error('Service indisponible ('+r.status+'). Réessaie plus tard.');return await r.json()}finally{clearTimeout(t)}}
function el(tag,text,cls){const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
async function loadOfficial(){if(officialSnapshot)return officialSnapshot;try{const r=await fetch('./data/official-stores.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json();if(!d||!Array.isArray(d.stores))throw Error();officialSnapshot=d;return d}catch(e){officialSnapshot={generatedAt:null,sources:{},stores:[]};return officialSnapshot}}
function officialRows(region,brands,snapshot){return snapshot.stores.filter(s=>s&&brands.includes(s.enseigne)&&String(s.regionCode||'')===String(region.code)).map(normalizeOfficial)}
function coverageNote(region,brands,snapshot){return brands.map(b=>{const source=snapshot.sources&&snapshot.sources[b],r=source&&source.regions&&source.regions[region.code];if(r&&r.status==='collected')return '';if(r&&r.status==='unsupported')return b+' : région non couverte';if(r)return b+' : collecte partielle ou indisponible';if(!source||!source.count)return b+' : aucune fiche officielle collectée';return ''}).filter(Boolean).join(' · ')}
async function enrich(s){if(complete(s))return s;if(Date.now()<cooldown)throw Error('Patiente quelques secondes avant un nouvel enrichissement.');let u;if(coords(s)){u='https://nominatim.openstreetmap.org/reverse?format=jsonv2&addressdetails=1&lat='+encodeURIComponent(s.lat)+'&lon='+encodeURIComponent(s.lon)}else if(s.adresse||s.ville){u='https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=1&countrycodes=fr&q='+encodeURIComponent([s.adresse,s.codePostal,s.ville,s.enseigne].filter(Boolean).join(', '))}else throw Error('Pas assez d’informations pour compléter cette fiche.');const r=await fetch(u,{headers:{'Accept-Language':'fr'}});if(r.status===429){cooldown=Date.now()+15000;throw Error('Service de géocodage occupé. Réessaie dans quelques secondes.')}if(!r.ok)throw Error('Complément d’adresse indisponible.');const raw=await r.json(),d=Array.isArray(raw)?raw[0]:raw;if(!d)throw Error('Adresse introuvable automatiquement.');const a=d.address||{};if(!coords(s)&&d.lat&&d.lon){s.lat=Number(d.lat);s.lon=Number(d.lon)}if(!s.ville)s.ville=a.city||a.town||a.village||a.municipality||'';if(!s.codePostal)s.codePostal=a.postcode||'';if(!s.adresse){const road=a.road||a.pedestrian||a.place||a.neighbourhood||'';s.adresse=[a.house_number,road].filter(Boolean).join(' ')||String(d.display_name||'').split(',').slice(0,2).join(', ').trim()}await sleep(1100);return s}
async function osmRows(region,brands){const data=await json('https://overpass.private.coffee/api/interpreter',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'data='+encodeURIComponent(query(region,brands))});return parseOSM(data,region,brands)}
function install(){const host=document.querySelector('#storesPanel .toolbar');if(!host||document.getElementById('regionDiscover'))return;const launch=el('button','＋ Ajouter une région','secondary');launch.id='regionDiscover';launch.type='button';host.append(launch);const d=el('dialog',null,'regionDialog');d.innerHTML='<div class="regionHeading"><div><small>ÉTENDRE MON SECTEUR</small><h2>Ajouter une région</h2></div><button type="button" aria-label="Fermer">✕</button></div><p>Les annuaires officiels des enseignes sont utilisés en priorité. OpenStreetMap sert uniquement à compléter les magasins absents ou les coordonnées.</p><label>Région<select id="regionChoice"><option value="">Charger les régions…</option></select></label><fieldset><legend>Enseignes recherchées</legend><div class="regionBrands"></div></fieldset><label class="checkitem"><input id="regionOsmComplement" type="checkbox" checked> Compléter avec OpenStreetMap si nécessaire</label><div class="regionOfficialLinks"></div><div class="regionActions"><button type="button" class="primary" id="regionSearch">Scanner la région</button><button type="button" class="secondary" id="regionCancel" hidden>Annuler</button></div><p class="regionStatus" role="status" aria-live="polite"></p><p class="regionSource">Priorité : annuaires Boulanger, Darty, Fnac, Conforama, Cuisinella et Carrefour. Les résultats OpenStreetMap sont marqués comme complément. Une fiche incomplète peut être enrichie automatiquement avant ajout. Vérifie toujours qu’un point de vente distribue bien les produits Samsung concernés.</p><div class="regionResults"></div><div class="regionFooter"><span id="regionSelected">Aucun magasin sélectionné</span><button type="button" class="primary" id="regionImport" disabled>Ajouter la sélection</button></div>';document.body.append(d);const select=d.querySelector('select'),search=d.querySelector('#regionSearch'),cancel=d.querySelector('#regionCancel'),status=d.querySelector('.regionStatus'),results=d.querySelector('.regionResults'),importBtn=d.querySelector('#regionImport');let searching=false;
BRANDS.forEach(b=>{const l=el('label'),c=el('input');c.type='checkbox';c.value=b;c.checked=b!=='Carrefour';l.append(c,document.createTextNode(b));d.querySelector('.regionBrands').append(l)});const links=d.querySelector('.regionOfficialLinks');BRANDS.forEach(b=>{const a=el('a',b+' ↗');a.href=OFFICIAL_URLS[b];a.target='_blank';a.rel='noopener noreferrer';a.style.marginRight='10px';links.append(a)});
function message(t){status.textContent=t}function stop(){if(controller)controller.abort()}function close(){stop();d.close()}d.querySelector('.regionHeading button').onclick=close;d.addEventListener('cancel',stop);cancel.onclick=stop;
function selectedRows(){return [...results.querySelectorAll('input[data-select]:checked')].map(n=>rows[Number(n.dataset.select)])}
function count(){const n=selectedRows().length;d.querySelector('#regionSelected').textContent=n+' magasin'+(n>1?'s':'')+' sélectionné'+(n>1?'s':'');importBtn.disabled=!n||searching}
function clear(){rows=[];results.replaceChildren();count()}select.onchange=clear;d.querySelector('.regionBrands').onchange=clear;
function render(){results.replaceChildren();rows.forEach((s,i)=>{const card=el('article',null,'regionResult'),check=el('input');check.type='checkbox';check.dataset.select=i;const exists=duplicate(s,root.state.stores);check.disabled=exists||!complete(s);check.setAttribute('aria-label','Sélectionner '+s.sourceName);check.onchange=count;const title=el('label',null,'regionResultTitle');title.append(check,document.createTextNode(s.sourceName));card.append(title);const badge=el('small',s.source&&s.source.indexOf('Annuaire officiel')===0?'✓ '+s.source:'↳ '+(s.source||'Source complémentaire'));if(s.sourceFetchedAt)badge.textContent+=' · collecté le '+new Date(s.sourceFetchedAt).toLocaleDateString('fr-FR');badge.style.display='block';badge.style.margin='4px 0 8px';card.append(badge);const addressLabel=el('label','Adresse'),address=el('input');address.value=s.adresse||'';address.placeholder='Adresse à compléter';address.disabled=exists;address.oninput=()=>{s.adresse=address.value.trim();check.disabled=exists||!complete(s);if(check.disabled)check.checked=false;count()};addressLabel.append(address);card.append(addressLabel);const cityLabel=el('label','Ville'),city=el('input');city.value=s.ville||'';city.placeholder='Ville à compléter';city.disabled=exists;city.oninput=()=>{s.ville=city.value.trim();check.disabled=exists||!complete(s);if(check.disabled)check.checked=false;count()};cityLabel.append(city);card.append(cityLabel);const actions=el('div',null,'row');if(s.sourceUrl){const a=el('a','Voir la source ↗');a.href=s.sourceUrl;a.target='_blank';a.rel='noopener noreferrer';actions.append(a)}if(!complete(s)&&!exists){const b=el('button','Compléter automatiquement','secondary');b.type='button';b.onclick=async()=>{b.disabled=true;b.textContent='Complément…';try{await enrich(s);render();message('Fiche complétée. Vérifie les informations avant ajout.')}catch(e){message(e.message)}finally{b.disabled=false}};actions.append(b)}card.append(actions,el('small',exists?'Déjà présent ou doublon probable':complete(s)?((s.codePostal||'')+' · coordonnées disponibles'):'Fiche incomplète · utilise « Compléter automatiquement »'));results.append(card)});count()}
launch.onclick=async()=>{d.showModal();if(regions.length||searching)return;controller=new AbortController();search.disabled=true;message('Chargement des régions…');try{const data=await json('https://geo.api.gouv.fr/regions');regions=(Array.isArray(data)?data:[]).filter(r=>/^\d{2}$/.test(r.code)&&typeof r.nom==='string').sort((a,b)=>a.nom.localeCompare(b.nom,'fr'));if(!regions.length)throw Error('Liste des régions indisponible.');select.replaceChildren(...regions.map(r=>{const o=el('option',r.nom);o.value=r.code;return o}));select.value=regions.some(r=>r.code==='84')?'84':regions[0].code;const snap=await loadOfficial();message(snap.generatedAt?'Base officielle mise à jour le '+new Date(snap.generatedAt).toLocaleDateString('fr-FR')+'.':'Base officielle en cours de première génération ; OpenStreetMap restera disponible en complément.')}catch(e){message(e.name==='AbortError'?'Chargement annulé.':e.message)}finally{search.disabled=false}};
search.onclick=async()=>{if(searching)return;const region=regions.find(r=>r.code===select.value),brands=[...d.querySelectorAll('.regionBrands input:checked')].map(c=>c.value);if(!region||!brands.length){message('Choisis une région et au moins une enseigne.');return}if(navigator.onLine===false){message('Cette recherche nécessite Internet.');return}clear();searching=true;search.disabled=true;select.disabled=true;d.querySelector('fieldset').disabled=true;cancel.hidden=false;controller=new AbortController();try{message('Lecture des annuaires officiels…');const snap=await loadOfficial();const official=officialRows(region,brands,snap);rows=official.slice();if(d.querySelector('#regionOsmComplement').checked){message(official.length+' résultat(s) officiel(s). Recherche des compléments OpenStreetMap…');try{const extra=await osmRows(region,brands);for(const s of extra)if(!duplicate(s,rows))rows.push(s)}catch(e){if(!official.length)throw e}}rows.sort((a,b)=>{const ao=a.source&&a.source.indexOf('Annuaire officiel')===0?0:1,bo=b.source&&b.source.indexOf('Annuaire officiel')===0?0:1;return ao-bo||(a.enseigne+a.ville).localeCompare(b.enseigne+b.ville,'fr')});render();const oc=rows.filter(s=>s.source&&s.source.indexOf('Annuaire officiel')===0).length,mc=rows.length-oc;message(rows.length?oc+' magasin(s) depuis les annuaires officiels'+(mc?' · '+mc+' complément(s) OpenStreetMap':'')+'.':'Aucun résultat. La source officielle peut être temporairement incomplète ; vérifie les liens des enseignes ci-dessus.');const warning=coverageNote(region,brands,snap);if(warning)message(status.textContent+' '+warning)}catch(e){message(e.name==='AbortError'?'Recherche annulée.':e.message)}finally{searching=false;search.disabled=false;select.disabled=false;d.querySelector('fieldset').disabled=false;cancel.hidden=true;count()}};
importBtn.onclick=async()=>{importBtn.disabled=true;try{const selected=selectedRows();for(const s of selected)if(!complete(s))await enrich(s);const n=commit(selected);if(typeof root.renderFilterControls==='function')root.renderFilterControls();root.renderAll();render();message(n+' magasin'+(n>1?'s':'')+' ajouté'+(n>1?'s':'')+' à ton secteur avec sauvegarde préalable.')}catch(e){message('Ajout interrompu : '+e.message)}finally{count()}};
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})(typeof window!=='undefined'?window:globalThis);

