/* Gestion du secteur : sélection exacte des magasins, import/export et conservation des historiques. */
(function(root){
'use strict';
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const BRANDS=['Boulanger','Darty','Fnac','Conforama','Cuisinella','Carrefour'];
const PAGE_SIZE=150;
const REGION_BY_DEPT={
'01':'Auvergne-Rhône-Alpes','03':'Auvergne-Rhône-Alpes','07':'Auvergne-Rhône-Alpes','15':'Auvergne-Rhône-Alpes','26':'Auvergne-Rhône-Alpes','38':'Auvergne-Rhône-Alpes','42':'Auvergne-Rhône-Alpes','43':'Auvergne-Rhône-Alpes','63':'Auvergne-Rhône-Alpes','69':'Auvergne-Rhône-Alpes','73':'Auvergne-Rhône-Alpes','74':'Auvergne-Rhône-Alpes',
'21':'Bourgogne-Franche-Comté','25':'Bourgogne-Franche-Comté','39':'Bourgogne-Franche-Comté','58':'Bourgogne-Franche-Comté','70':'Bourgogne-Franche-Comté','71':'Bourgogne-Franche-Comté','89':'Bourgogne-Franche-Comté','90':'Bourgogne-Franche-Comté',
'22':'Bretagne','29':'Bretagne','35':'Bretagne','56':'Bretagne','18':'Centre-Val de Loire','28':'Centre-Val de Loire','36':'Centre-Val de Loire','37':'Centre-Val de Loire','41':'Centre-Val de Loire','45':'Centre-Val de Loire',
'08':'Grand Est','10':'Grand Est','51':'Grand Est','52':'Grand Est','54':'Grand Est','55':'Grand Est','57':'Grand Est','67':'Grand Est','68':'Grand Est','88':'Grand Est',
'02':'Hauts-de-France','59':'Hauts-de-France','60':'Hauts-de-France','62':'Hauts-de-France','80':'Hauts-de-France',
'75':'Île-de-France','77':'Île-de-France','78':'Île-de-France','91':'Île-de-France','92':'Île-de-France','93':'Île-de-France','94':'Île-de-France','95':'Île-de-France',
'14':'Normandie','27':'Normandie','50':'Normandie','61':'Normandie','76':'Normandie','16':'Nouvelle-Aquitaine','17':'Nouvelle-Aquitaine','19':'Nouvelle-Aquitaine','23':'Nouvelle-Aquitaine','24':'Nouvelle-Aquitaine','33':'Nouvelle-Aquitaine','40':'Nouvelle-Aquitaine','47':'Nouvelle-Aquitaine','64':'Nouvelle-Aquitaine','79':'Nouvelle-Aquitaine','86':'Nouvelle-Aquitaine','87':'Nouvelle-Aquitaine',
'09':'Occitanie','11':'Occitanie','12':'Occitanie','30':'Occitanie','31':'Occitanie','32':'Occitanie','34':'Occitanie','46':'Occitanie','48':'Occitanie','65':'Occitanie','66':'Occitanie','81':'Occitanie','82':'Occitanie',
'44':'Pays de la Loire','49':'Pays de la Loire','53':'Pays de la Loire','72':'Pays de la Loire','85':'Pays de la Loire','04':"Provence-Alpes-Côte d'Azur",'05':"Provence-Alpes-Côte d'Azur",'06':"Provence-Alpes-Côte d'Azur",'13':"Provence-Alpes-Côte d'Azur",'83':"Provence-Alpes-Côte d'Azur",'84':"Provence-Alpes-Côte d'Azur",'2A':'Corse','2B':'Corse'};
function fp(s){return [norm(s.enseigne),norm(s.codePostal||s.dept),norm(s.ville),norm(s.adresse)].join('|')}
function db(){return root.__chefStorage||root.localStorage}
function clone(x){return JSON.parse(JSON.stringify(x))}
function dedupe(rows){const out=[];rows.forEach(s=>{if(!s||!s.id)return;const k=fp(s);if(!out.some(x=>String(x.id)===String(s.id)||fp(x)===k))out.push(clone(s))});return out}
function regionOf(s){return s.region||REGION_BY_DEPT[String(s.dept||'')]||''}
async function catalog(){let rows=(root.state&&root.state.stores?root.state.stores:[]).map(clone);try{if(root.ChefNationalSectors&&root.ChefNationalSectors.loadCatalog)rows=rows.concat(await root.ChefNationalSectors.loadCatalog())}catch(e){}rows=dedupe(rows);rows.forEach(s=>{if(!s.region)s.region=regionOf(s)});return rows}
function migrateMap(map,oldId,newId){if(!map||oldId===newId)return;if(map[oldId]!==undefined&&map[newId]===undefined)map[newId]=clone(map[oldId])}
function applyExact(name,selected){
 if(!root.state||!root.ChefReliability)throw Error('Application pas encore prête.');
 if(!selected.length)throw Error('Sélectionne au moins un magasin.');
 const R=root.ChefReliability,store=db(),bundle=R.capture(root.state,store),old=bundle.state.stores||[],oldById=new Map(old.map(s=>[String(s.id),s])),oldByFp=new Map(old.map(s=>[fp(s),s]));
 const next=selected.map(s=>{const prev=oldById.get(String(s.id))||oldByFp.get(fp(s));if(!prev)return clone(s);const row=Object.assign({},clone(s),{freq:prev.freq||s.freq,intervalDays:prev.intervalDays||s.intervalDays,priority:prev.priority||s.priority,active:prev.active!==false,products:prev.products||s.products});for(const key of ['visits','notes','included','excluded','locks'])migrateMap(bundle.state[key],String(prev.id),String(row.id));return row});
 const validIds=new Set(next.map(s=>String(s.id)));if(Array.isArray(bundle.state.appointments))bundle.state.appointments=bundle.state.appointments.map(a=>{const prev=oldById.get(String(a.storeId)),matched=prev&&next.find(s=>fp(s)===fp(prev));return matched?Object.assign({},a,{storeId:String(matched.id)}):a}).filter(a=>validIds.has(String(a.storeId)));
 bundle.state.stores=next;bundle.state.plan={};bundle.state.profile=bundle.state.profile||{};bundle.state.profile.sectorName=name||'Mon secteur';bundle.state.profile.nationalSector={name:bundle.state.profile.sectorName,mode:'exact',storeIds:next.map(s=>String(s.id)),fingerprints:next.map(fp)};
 R.checkpoint('Avant modification du secteur',store,bundle);R.persist(bundle,store);root.state=bundle.state;if(typeof root.initControls==='function')root.initControls();if(typeof root.renderAll==='function')root.renderAll();if(typeof root.renderHeader==='function')root.renderHeader();return next.length
}
function exportSector(name,selected){const payload={format:'ChefSecteurSector',version:1,name:name||'Mon secteur',createdAt:new Date().toISOString(),stores:selected.map(clone)};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='chef-secteur-'+norm(payload.name||'secteur')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
function parseImport(text){const d=JSON.parse(text);if(!d||d.format!=='ChefSecteurSector'||d.version!==1||!Array.isArray(d.stores))throw Error('Fichier de secteur non reconnu.');if(!d.stores.length)throw Error('Le fichier ne contient aucun magasin.');return d}
function install(){
 const host=document.querySelector('#storesPanel .toolbar');if(!host||document.getElementById('sectorAdminBtn'))return false;const old=document.getElementById('nationalSectorBtn');if(old)old.style.display='none';
 const btn=document.createElement('button');btn.id='sectorAdminBtn';btn.type='button';btn.className='secondary';btn.textContent='⚙️ Gérer mon secteur';host.append(btn);
 const d=document.createElement('dialog');d.className='catalogDialog';d.innerHTML=`<div class="catalogHead"><div><small>MON SECTEUR</small><h2>Gérer mon secteur</h2></div><button class="catalogClose" type="button">✕</button></div><div class="catalogBody"><div class="notice">Ajoutez ou retirez les magasins de votre secteur, puis enregistrez votre sélection.</div><label>Nom du secteur<input id="saName" placeholder="Mon secteur"></label><div class="catalogTools"><input id="saSearch" placeholder="Rechercher un magasin, une ville ou une enseigne…"></div><section id="saBrandChooser" style="margin:14px 0 16px;padding:14px;border:1px solid #dbe7fb;border-radius:18px;background:rgba(255,255,255,.72)"><div style="font-size:14px;font-weight:800;margin-bottom:9px">Choisir mes magasins</div><div class="row"><select id="saBrandFilter" class="grow"><option value="all">Toutes les enseignes</option>${BRANDS.map(b=>`<option value="${esc(b)}">${esc(b)}</option>`).join('')}</select></div></section><div><b>Ajouter une zone</b><div class="row" style="margin-top:8px;align-items:center"><select id="saRegionPick" class="grow"><option value="">Choisir une région…</option></select><button type="button" class="secondary" id="saAddRegion">+ Région</button></div><div class="row" style="margin-top:8px;align-items:center"><select id="saDeptPick" class="grow"><option value="">Choisir un département…</option></select><button type="button" class="secondary" id="saAddDept">+ Département</button></div><div class="row" style="margin-top:8px"><span id="saDeptSelected" class="tiny">Tous les départements</span><button type="button" class="secondary" id="saClearDept" style="display:none">Effacer</button></div></div><div class="catalogActions"><button type="button" class="secondary" id="saAll">Tout sélectionner affiché</button><button type="button" class="secondary" id="saNone">Tout retirer affiché</button><button type="button" class="secondary" id="saExport">Exporter mon secteur</button><button type="button" class="secondary" id="saImport">Importer un secteur</button><input id="saFile" type="file" accept="application/json,.json" hidden></div><div class="notice">Conseil : vérifiez régulièrement que les magasins affichés correspondent bien à votre secteur actuel.</div><div id="saStats" class="catalogStats"></div><div id="saList" class="catalogList"></div><div style="display:flex;justify-content:center;padding:12px 0"><button type="button" class="secondary" id="saMore" style="display:none">Afficher plus</button></div><div class="catalogActions" style="position:sticky;bottom:0;background:#f5f8fc;padding:12px 0"><button type="button" class="primary" id="saSave">Enregistrer ce secteur</button></div></div>`;document.body.append(d);
 const q=s=>d.querySelector(s),name=q('#saName'),search=q('#saSearch'),brand=q('#saBrandFilter'),regionPick=q('#saRegionPick'),deptPick=q('#saDeptPick'),deptSelected=q('#saDeptSelected'),clearDept=q('#saClearDept'),list=q('#saList'),stats=q('#saStats'),more=q('#saMore'),file=q('#saFile');let rows=[],selected=new Set(),selectedDepts=new Set(),renderLimit=PAGE_SIZE;
 function visible(){const t=norm(search.value),wanted=brand.value;return rows.filter(s=>(!selectedDepts.size||selectedDepts.has(String(s.dept||'')))&&(wanted==='all'||String(s.enseigne||'')===wanted)&&(!t||norm([s.enseigne,s.sourceName,s.ville,s.adresse,s.codePostal,s.dept].join(' ')).includes(t)))}
 function renderFilters(){const departments=[...new Set(rows.map(s=>String(s.dept||'')).filter(Boolean))].sort(),regions=[...new Set(rows.map(regionOf).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr'));regionPick.innerHTML='<option value="">Choisir une région…</option>'+regions.map(x=>'<option value="'+esc(x)+'">'+esc(x)+'</option>').join('');const available=departments.filter(x=>!selectedDepts.has(x));deptPick.innerHTML='<option value="">Choisir un département…</option>'+available.map(x=>'<option value="'+esc(x)+'">'+esc(x)+'</option>').join('');const chosen=[...selectedDepts].sort();deptSelected.textContent=chosen.length?'Départements ajoutés : '+chosen.join(', '):'Tous les départements';clearDept.style.display=chosen.length?'inline-block':'none'}
 function updateStats(v,shown){stats.textContent=selected.size+' magasin(s) dans mon secteur · '+v.length+' correspondant(s) · '+shown+' affiché(s)'}
 function render(){const v=visible(),shown=Math.min(v.length,renderLimit);updateStats(v,shown);list.innerHTML='';v.slice(0,shown).forEach(s=>{const card=document.createElement('label');card.className='catalogCard';card.style.display='grid';card.style.gridTemplateColumns='auto 1fr';card.style.gap='10px';card.innerHTML='<input type="checkbox" '+(selected.has(String(s.id))?'checked':'')+'><div><h3>'+esc(s.sourceName||((s.enseigne||'')+' '+(s.ville||'')))+'</h3><div class="catalogMeta">'+esc([s.adresse,s.codePostal||s.dept,s.ville].filter(Boolean).join(' · '))+'</div><div class="catalogMeta">'+esc(s.enseigne||'')+'</div></div>';const c=card.querySelector('input');c.onchange=()=>{if(c.checked)selected.add(String(s.id));else selected.delete(String(s.id));updateStats(v,shown)};list.append(card)});if(!v.length)list.innerHTML='<div class="catalogCard">Aucun magasin correspondant.</div>';more.style.display=shown<v.length?'inline-block':'none';if(shown<v.length)more.textContent='Afficher plus ('+(v.length-shown)+' restant'+(v.length-shown>1?'s':'')+')'}
 function resetRender(){renderLimit=PAGE_SIZE;render()}
 async function open(){d.showModal();stats.textContent='Chargement du catalogue…';rows=await catalog();const current=root.state&&root.state.stores||[];selected=new Set(current.map(s=>String(s.id)));selectedDepts=new Set();renderLimit=PAGE_SIZE;brand.value='all';name.value=(root.state&&root.state.profile&&root.state.profile.sectorName)||'Mon secteur';renderFilters();render()}
 btn.onclick=open;q('.catalogClose').onclick=()=>d.close();search.oninput=resetRender;brand.onchange=resetRender;
 q('#saAddRegion').onclick=()=>{const r=regionPick.value;if(!r)return;rows.filter(s=>regionOf(s)===r).forEach(s=>{if(s.dept)selectedDepts.add(String(s.dept))});renderFilters();resetRender()};
 q('#saAddDept').onclick=()=>{const value=deptPick.value;if(!value)return;selectedDepts.add(value);renderFilters();resetRender()};clearDept.onclick=()=>{selectedDepts.clear();renderFilters();resetRender()};
 q('#saAll').onclick=()=>{visible().forEach(s=>selected.add(String(s.id)));render()};q('#saNone').onclick=()=>{visible().forEach(s=>selected.delete(String(s.id)));render()};more.onclick=()=>{renderLimit+=PAGE_SIZE;render()};
 q('#saSave').onclick=()=>{try{const picked=rows.filter(s=>selected.has(String(s.id)));const n=applyExact(name.value.trim()||'Mon secteur',picked);stats.textContent=n+' magasins enregistrés dans ton secteur.';setTimeout(()=>d.close(),700)}catch(e){stats.textContent='Enregistrement impossible : '+e.message}};
 q('#saExport').onclick=()=>exportSector(name.value.trim()||'Mon secteur',rows.filter(s=>selected.has(String(s.id))));q('#saImport').onclick=()=>file.click();file.onchange=async()=>{try{const f=file.files&&file.files[0];if(!f)return;const data=parseImport(await f.text());rows=dedupe(rows.concat(data.stores));rows.forEach(s=>{if(!s.region)s.region=regionOf(s)});selected=new Set(data.stores.map(s=>String(s.id)));selectedDepts=new Set();renderLimit=PAGE_SIZE;brand.value='all';name.value=data.name||name.value;renderFilters();render();stats.textContent='Secteur importé. Vérifie puis appuie sur « Enregistrer ce secteur ».'}catch(e){stats.textContent='Import impossible : '+e.message}finally{file.value=''}};return true
}
root.ChefSectorAdmin={catalog,applyExact,parseImport};function boot(){if(!install())setTimeout(boot,250)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})(typeof window!=='undefined'?window:globalThis);
