/* Gestion du secteur : sélection exacte des magasins, import/export et conservation des historiques. */
(function(root){
'use strict';
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
function fp(s){return [norm(s.enseigne),norm(s.codePostal||s.dept),norm(s.ville),norm(s.adresse)].join('|')}
function db(){return root.__chefStorage||root.localStorage}
function clone(x){return JSON.parse(JSON.stringify(x))}
function dedupe(rows){const out=[];rows.forEach(s=>{if(!s||!s.id)return;const k=fp(s);if(!out.some(x=>String(x.id)===String(s.id)||fp(x)===k))out.push(clone(s))});return out}
async function catalog(){let rows=(root.state&&root.state.stores?root.state.stores:[]).map(clone);try{if(root.ChefNationalSectors&&root.ChefNationalSectors.loadCatalog)rows=rows.concat(await root.ChefNationalSectors.loadCatalog())}catch(e){}return dedupe(rows)}
function migrateMap(map,oldId,newId){if(!map||oldId===newId)return;if(map[oldId]!==undefined&&map[newId]===undefined)map[newId]=clone(map[oldId])}
function applyExact(name,selected){
 if(!root.state||!root.ChefReliability)throw Error('Application pas encore prête.');
 if(!selected.length)throw Error('Sélectionne au moins un magasin.');
 const R=root.ChefReliability,store=db(),bundle=R.capture(root.state,store),old=bundle.state.stores||[],oldById=new Map(old.map(s=>[String(s.id),s])),oldByFp=new Map(old.map(s=>[fp(s),s]));
 const next=selected.map(s=>{const prev=oldById.get(String(s.id))||oldByFp.get(fp(s));if(!prev)return clone(s);const row=Object.assign({},clone(s),{freq:prev.freq||s.freq,intervalDays:prev.intervalDays||s.intervalDays,priority:prev.priority||s.priority,active:prev.active!==false,products:prev.products||s.products});
   for(const key of ['visits','notes','included','excluded','locks'])migrateMap(bundle.state[key],String(prev.id),String(row.id));return row});
 const validIds=new Set(next.map(s=>String(s.id)));
 if(Array.isArray(bundle.state.appointments))bundle.state.appointments=bundle.state.appointments.map(a=>{const prev=oldById.get(String(a.storeId)),matched=prev&&next.find(s=>fp(s)===fp(prev));return matched?Object.assign({},a,{storeId:String(matched.id)}):a}).filter(a=>validIds.has(String(a.storeId)));
 bundle.state.stores=next;bundle.state.plan={};bundle.state.profile=bundle.state.profile||{};bundle.state.profile.sectorName=name||'Mon secteur';bundle.state.profile.nationalSector={name:bundle.state.profile.sectorName,mode:'exact',storeIds:next.map(s=>String(s.id)),fingerprints:next.map(fp)};
 R.checkpoint('Avant modification du secteur',store,bundle);R.persist(bundle,store);root.state=bundle.state;
 if(typeof root.initControls==='function')root.initControls();if(typeof root.renderAll==='function')root.renderAll();if(typeof root.renderHeader==='function')root.renderHeader();return next.length
}
function exportSector(name,selected){const payload={format:'ChefSecteurSector',version:1,name:name||'Mon secteur',createdAt:new Date().toISOString(),stores:selected.map(clone)};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='chef-secteur-'+norm(payload.name||'secteur')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
function parseImport(text){const d=JSON.parse(text);if(!d||d.format!=='ChefSecteurSector'||d.version!==1||!Array.isArray(d.stores))throw Error('Fichier de secteur non reconnu.');if(!d.stores.length)throw Error('Le fichier ne contient aucun magasin.');return d}
function install(){
 const host=document.querySelector('#storesPanel .toolbar');if(!host||document.getElementById('sectorAdminBtn'))return false;
 const old=document.getElementById('nationalSectorBtn');if(old)old.style.display='none';
 const btn=document.createElement('button');btn.id='sectorAdminBtn';btn.type='button';btn.className='secondary';btn.textContent='⚙️ Gérer mon secteur';host.append(btn);
 const d=document.createElement('dialog');d.className='catalogDialog';d.innerHTML=`<div class="catalogHead"><div><small>MON SECTEUR</small><h2>Gérer mon secteur</h2></div><button class="catalogClose" type="button">✕</button></div><div class="catalogBody"><div class="notice">Ajoutez, retirez ou modifiez les magasins de votre secteur. Vous pouvez aussi importer ou exporter votre sélection pour la retrouver facilement sur un autre appareil.</div><label>Nom du secteur<input id="saName" placeholder="Mon secteur"></label><div class="catalogTools"><input id="saSearch" placeholder="Rechercher magasin, ville, département…"><select id="saBrand"><option value="">Toutes les enseignes</option></select><select id="saDept"><option value="">Tous les départements</option></select></div><div class="catalogActions"><button type="button" class="secondary" id="saAll">Tout sélectionner affiché</button><button type="button" class="secondary" id="saNone">Tout retirer affiché</button><button type="button" class="secondary" id="saExport">Exporter mon secteur</button><button type="button" class="secondary" id="saImport">Importer un secteur</button><input id="saFile" type="file" accept="application/json,.json" hidden></div><div class="notice">Conseil : vérifiez régulièrement que les magasins affichés correspondent bien à votre secteur actuel.</div><div id="saStats" class="catalogStats"></div><div id="saList" class="catalogList"></div><div class="catalogActions" style="position:sticky;bottom:0;background:#f5f8fc;padding:12px 0"><button type="button" class="primary" id="saSave">Enregistrer ce secteur</button></div></div>`;document.body.append(d);
 const q=s=>d.querySelector(s),name=q('#saName'),search=q('#saSearch'),brand=q('#saBrand'),dept=q('#saDept'),list=q('#saList'),stats=q('#saStats'),file=q('#saFile');let rows=[],selected=new Set();
 function visible(){const t=norm(search.value),b=brand.value,p=dept.value;return rows.filter(s=>(!b||s.enseigne===b)&&(!p||String(s.dept||'')===p)&&(!t||norm([s.enseigne,s.sourceName,s.ville,s.adresse,s.codePostal,s.dept].join(' ')).includes(t)))}
 function renderFilters(){const brands=[...new Set(rows.map(s=>s.enseigne).filter(Boolean))].sort(),deps=[...new Set(rows.map(s=>String(s.dept||'')).filter(Boolean))].sort();brand.innerHTML='<option value="">Toutes les enseignes</option>'+brands.map(x=>'<option>'+esc(x)+'</option>').join('');dept.innerHTML='<option value="">Tous les départements</option>'+deps.map(x=>'<option>'+esc(x)+'</option>').join('')}
 function render(){const v=visible();stats.textContent=selected.size+' magasin(s) dans mon secteur · '+v.length+' affiché(s)';list.innerHTML='';v.slice(0,500).forEach(s=>{const card=document.createElement('label');card.className='catalogCard';card.style.display='grid';card.style.gridTemplateColumns='auto 1fr';card.style.gap='10px';card.innerHTML='<input type="checkbox" '+(selected.has(String(s.id))?'checked':'')+'><div><h3>'+esc(s.sourceName||((s.enseigne||'')+' '+(s.ville||'')))+'</h3><div class="catalogMeta">'+esc([s.adresse,s.codePostal||s.dept,s.ville].filter(Boolean).join(' · '))+'</div><div class="catalogMeta">'+esc(s.enseigne||'')+(s.source?' · '+esc(s.source):'')+'</div></div>';const c=card.querySelector('input');c.onchange=()=>{if(c.checked)selected.add(String(s.id));else selected.delete(String(s.id));stats.textContent=selected.size+' magasin(s) dans mon secteur · '+v.length+' affiché(s)'};list.append(card)});if(!v.length)list.innerHTML='<div class="catalogCard">Aucun magasin correspondant.</div>'}
 async function open(){d.showModal();stats.textContent='Chargement du catalogue…';rows=await catalog();const current=root.state&&root.state.stores||[];selected=new Set(current.map(s=>String(s.id)));name.value=(root.state&&root.state.profile&&root.state.profile.sectorName)||'Mon secteur';renderFilters();render()}
 btn.onclick=open;q('.catalogClose').onclick=()=>d.close();search.oninput=render;brand.onchange=render;dept.onchange=render;
 q('#saAll').onclick=()=>{visible().forEach(s=>selected.add(String(s.id)));render()};q('#saNone').onclick=()=>{visible().forEach(s=>selected.delete(String(s.id)));render()};
 q('#saSave').onclick=()=>{try{const picked=rows.filter(s=>selected.has(String(s.id)));const n=applyExact(name.value.trim()||'Mon secteur',picked);stats.textContent=n+' magasins enregistrés dans ton secteur.';setTimeout(()=>d.close(),700)}catch(e){stats.textContent='Enregistrement impossible : '+e.message}};
 q('#saExport').onclick=()=>exportSector(name.value.trim()||'Mon secteur',rows.filter(s=>selected.has(String(s.id))));q('#saImport').onclick=()=>file.click();file.onchange=async()=>{try{const f=file.files&&file.files[0];if(!f)return;const data=parseImport(await f.text());rows=dedupe(rows.concat(data.stores));selected=new Set(data.stores.map(s=>String(s.id)));name.value=data.name||name.value;renderFilters();render();stats.textContent='Secteur importé. Vérifie puis appuie sur « Enregistrer ce secteur ».'}catch(e){stats.textContent='Import impossible : '+e.message}finally{file.value=''}};
 return true
}
root.ChefSectorAdmin={catalog,applyExact,parseImport};function boot(){if(!install())setTimeout(boot,250)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})(typeof window!=='undefined'?window:globalThis);
