const fs=require('fs');
const assert=require('assert');
const index=fs.readFileSync('index.html','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const indexMatch=index.match(/const BUILD_REV='([^']+)'/);
const swMatch=sw.match(/const BUILD_REV = "([^"]+)"/);
assert(indexMatch,'BUILD_REV absent de index.html');
assert(swMatch,'BUILD_REV absent de sw.js');
assert.strictEqual(indexMatch[1],swMatch[1],'index.html et sw.js doivent partager le même BUILD_REV');
assert(!index.includes('20260910-assistant-visits1'),'ancienne révision encore présente dans index.html');
assert(!sw.includes('20260910-assistant-visits1'),'ancienne révision encore présente dans sw.js');
console.log('build revision ok:',indexMatch[1]);
