const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const source=fs.readFileSync(__dirname+'/../src/chef-secteur.html','utf8').match(/<script id="google-calendar-js">([\s\S]*?)<\/script>/)[1];
function env(){const map=new Map([['chef_secteur_google_token_v2','token']]),elements={};const storage={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};
const ctx={state:{settings:{weekDate:'2026-09-07'},calendarEvents:[{id:'old',date:'2026-09-08',start:'2026-09-08T09:00:00',end:'2026-09-08T10:00:00'}],calendarLastSync:'2026-09-01T08:00:00Z'},sessionStorage:storage,localStorage:storage,document:{getElementById:id=>elements[id]||(elements[id]={textContent:'',classList:{toggle(){}}})},navigator:{onLine:true},Date,JSON,AbortController,CustomEvent:class{},setTimeout:()=>1,clearTimeout(){},setInterval(){},todayISO:()=> '2026-09-08',save(){},renderAll(){}};
ctx.window=ctx;ctx.addEventListener=()=>{};ctx.dispatchEvent=()=>{};ctx.fetch=async url=>({ok:true,status:200,json:async()=>url.includes('calendarList')?{items:[{id:'main',summary:'Agenda'}]}:{items:[{id:'new',summary:'RDV',start:{dateTime:'2026-09-08T13:00:00+02:00'},end:{dateTime:'2026-09-08T14:00:00+02:00'}}]}});vm.runInNewContext(source,ctx);return ctx;}
(async()=>{
let c=env();let result=await c.syncGoogleCalendar();assert(result.ok);assert.equal(c.chefGoogleStatus.connected,true);assert.equal(c.state.calendarEvents[0].id,'main:new');assert(c.state.calendarLastSync>'2026-09-01');
c=env();c.fetch=async()=>({status:401,ok:false});result=await c.syncGoogleCalendar();assert.equal(result.ok,false);assert.equal(c.chefGoogleStatus.phase,'expired');assert.equal(c.state.calendarEvents[0].id,'old');assert.equal(c.state.calendarLastSync,'2026-09-01T08:00:00Z');assert.equal(c.sessionStorage.getItem('chef_secteur_google_token_v2'),null);
c=env();c.navigator.onLine=false;c.fetch=async()=>{throw Error('offline')};await c.syncGoogleCalendar();assert.equal(c.chefGoogleStatus.phase,'offline');assert.equal(c.state.calendarEvents[0].id,'old');
c=env();c.sessionStorage.removeItem('chef_secteur_google_token_v2');await c.syncGoogleCalendar(true);assert.equal(c.chefGoogleStatus.connected,false);
c=env();c.sessionStorage.setItem('chef_google_token_expiry_v1','1');await c.syncGoogleCalendar();assert.equal(c.chefGoogleStatus.phase,'expired');
c=env();let n=0;c.fetch=async()=>{if(n++===0)return {status:200,ok:true,json:async()=>({items:[{id:'a'},{id:'b'}]})};if(n===2)return {status:200,ok:true,json:async()=>({items:[]})};throw Error('calendar failure')};await c.syncGoogleCalendar();assert.equal(c.state.calendarEvents[0].id,'old');assert.equal(c.chefGoogleStatus.connected,false);
c=env();c.save=()=>{throw Error('quota')};await c.syncGoogleCalendar();assert.equal(c.state.calendarEvents[0].id,'old');assert.equal(c.state.calendarLastSync,'2026-09-01T08:00:00Z');
c=env();let release;c.fetch=()=>new Promise(resolve=>{release=resolve});const pending=c.syncGoogleCalendar();c.disconnectGoogleCalendar();release({status:200,ok:true,json:async()=>({items:[]})});await pending;assert.equal(c.state.calendarEvents.length,0);assert.equal(c.chefGoogleStatus.connected,false);
console.log('PASS: successful sync; expired/absent tokens; offline; partial failure; storage failure; disconnect during request. Cached events never falsely reported as fresh.');
})().catch(e=>{console.error(e);process.exitCode=1});
