const assert=require('node:assert/strict');
const fs=require('node:fs');
const events=require('../store-runner-professional-events.js');
const date={id:'safe-event-1',kind:'Séminaire',title:'Séminaire 2026',
 startDate:'2026-10-19',endDate:'2026-10-21',location:'Saint-Ouen',
 address:'10, rue des Réunions; Saint-Ouen',notes:'Réunion\nSalle 3'};
const ics=events.toICS(date);
const unfolded=ics.replace(/\r\n[ \t]/g,'');
assert(ics.startsWith('BEGIN:VCALENDAR\r\nVERSION:2.0'));
assert(ics.endsWith('END:VCALENDAR\r\n'));
assert.match(unfolded,/BEGIN:VEVENT\r\n/);
assert.match(unfolded,/DTSTART;VALUE=DATE:20261019\r\n/);
assert.match(unfolded,/DTEND;VALUE=DATE:20261022\r\n/,'date de fin exclusive pour 3 jours');
assert.match(unfolded,/SUMMARY:Séminaire 2026/);
assert(unfolded.includes('LOCATION:10\\, rue des Réunions\\; Saint-Ouen\\, Saint-Ouen'));
assert(unfolded.includes('DESCRIPTION:Séminaire\\nRéunion\\nSalle 3'));
assert(ics.includes('UID:sr-safe-event-1@store-runner.fr'));
assert(!ics.includes('20261023'),'la durée ne doit pas déborder');
assert.throws(()=>events.toICS({...date,endDate:'2026-10-18'}),/période/);
const withEmoji=events.toICS({...date,title:'🎓 Réunion, briefing; école',notes:'Longue '.repeat(75)});
assert(withEmoji.replace(/\r\n /g,'').includes('SUMMARY:🎓 Réunion\\, briefing\\; école'));
assert(withEmoji.split('\r\n').every(line=>Buffer.byteLength(line,'utf8')<=75),'les lignes longues sont repliées suivant le format iCalendar');
const monthly=fs.readFileSync('planning-pro-plus.js','utf8');
assert(monthly.includes('state.professionalEvents'),'le calendrier mensuel doit afficher les événements locaux');
assert(monthly.includes('state.calendarEvents'),'le calendrier mensuel doit afficher les événements Google conservés');
assert(monthly.includes('window.chefSecteurEventCoversDate'),'Google reste propriétaire des bornes all-day multi-jours');
assert(monthly.includes('store-runner:calendar-updated'),'les retours de synchronisation réactualisent la vue');
assert(monthly.includes('proMonthStatus'),'l’état Google est visible même quand la vue mensuelle est repliée');
const oauth=fs.readFileSync('calendar-oauth.js','utf8');
assert(oauth.includes('lecture seule'),'Google reste en lecture seule');
assert.equal(JSON.parse(fs.readFileSync('version.json','utf8')).displayVersion,'278');
console.log('V278 : calendrier Apple .ics et Google/local sans mutation, dates exclusives, repli UTF-8 et état visible : OK');