const assert=require('node:assert/strict');
const fs=require('fs');
const UI=require('../performance-ui-v190.js');
const fields=UI.suggestedStoreFields({retailer:'BOULANGER',site:'BOULANGER AUBIERE / Clermont'});
assert.equal(fields.enseigne,'Boulanger');
assert.equal(fields.ville,'AUBIERE');
assert.equal(fields.sourceName,'BOULANGER AUBIERE / Clermont');
const ui=fs.readFileSync('performance-ui-v190.js','utf8');
assert.match(ui,/Ajouter ce magasin à mon secteur/);
assert.match(ui,/RegionStores/);
assert.match(ui,/R\.commit\(\[store\]\)/);
assert.match(ui,/P\.rememberMatch\(db\(\),r\.key,store\.id\)/);
assert.match(ui,/Doublon probable/);
assert.match(ui,/rattaché.*sur/);
assert.doesNotMatch(ui,/state\.plan\s*=|state\.plan\[/,'V209 ne doit jamais modifier le planning');
const profile=fs.readFileSync('profile-controller.js','utf8');
assert.match(profile,/window\.StoreRunnerGeocode=\{forward:forwardGeocode,reverse:reverseGeocode\}/);
assert.match(profile,/postcode:postcode/);
console.log('performance-store-reconcile-v209: OK · Aubière prérempli, création explicite, dédoublonnage et mapping persisté');
