const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const terrain=require('../terrain-planning-v1.js');
const read=f=>fs.readFileSync(__dirname+'/../'+f,'utf8');
const DAYS=['Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'],WORK=DAYS.slice(0,5);
const key=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');
const clone=x=>JSON.parse(JSON.stringify(x));
const plan=()=>Object.fromEntries(DAYS.map(d=>[d,[]]));
function fields(shown,chosen,edited){return {weekDate:{value:shown},rangeStart:{value:chosen||shown,dataset:{snailUserEdited:edited?'1':''}},rangeEnd:{value:''}}}
function resolve(now,shown,chosen,edited,extra){const state=Object.assign({settings:{weekDate:shown,days:WORK},calendarEvents:[]},extra||{}),f=fields(shown,chosen,edited);return key(terrain.resolveSnailStart(state,{getElementById:id=>f[id]},new Date(now+'T12:00:00')))}
function clock(now){const RealDate=Date;return class extends RealDate{constructor(...args){super(...(args.length?args:[now+'T12:00:00']))}static now(){return new RealDate(now+'T12:00:00').getTime()}}}
function runtime(now,opts={}){
  const stores=Array.from({length:70},(_,i)=>({id:'s'+i,enseigne:'Fnac',ville:'Ville '+i,active:true,lat:45+i*.00001,lon:4,priority:3}));
  const state={profile:{baseLat:45,baseLon:4},settings:{weekDate:opts.shown||'2026-09-28',days:WORK,target:20,maxVisitsPerDay:4,startTime:'08:00',endTime:'20:00',visitMinutes:30},stores,plan:opts.plan||plan(),locks:opts.locks||{},appointments:[],included:{},excluded:{},calendarEvents:[],manualWeekEdits:{},hotelReservations:{}};
  const f=fields(state.settings.weekDate),values=new Map(),events=[];
  const storage={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,String(v)),flush:async()=>{}};
  const ctx={console,Date:clock(now),JSON,Math,Object,Array,String,Number,Set,Map,RegExp,Promise,document:{readyState:'loading',addEventListener(){},dispatchEvent:e=>events.push(e),getElementById:id=>f[id]||null,querySelector(){return null},querySelectorAll(){return[]}},addEventListener(){},dispatchEvent(){},setTimeout(){},CustomEvent:class{constructor(type,init){this.type=type;this.detail=init&&init.detail}},state,__chefStorage:storage,save(){},initControls(){},renderAll(){},hav:(a,b)=>Math.abs(a.lat-b.lat)*111,havBase:s=>Math.abs(s.lat-state.profile.baseLat)*111,baseObj:()=>({lat:state.profile.baseLat,lon:state.profile.baseLon}),includedByFilters:()=>true,storeVisitCredit:()=>1,storeRunnerLockDayForWeek:(id,w)=>state.locks[id]&&state.locks[id].week===w?state.locks[id].day:''};
  ctx.ChefReliability={checkpoint(){},capture:st=>({state:clone(st),archive:JSON.parse(storage.getItem('chef_sector_plan_archive_v1')||'{}')}),persist:(b)=>{storage.setItem('chef_sector_plan_archive_v1',JSON.stringify(b.archive));storage.setItem('chef_sector_range_v1',JSON.stringify(b.range))}};
  ctx.window=ctx;vm.runInNewContext(read('terrain-planning-v1.js'),ctx);
  return{ctx,f,stores,events,storage};
}
function controller(now,shown,location){
  const trace=[],f=fields(shown),button={disabled:false,insertAdjacentElement(){}};f.planningGenerateStatus={textContent:'',style:{},dataset:{}};const doc={readyState:'loading',addEventListener(){},getElementById:id=>f[id]||null,querySelector:()=>button,querySelectorAll:()=>[button]};
  const state={profile:{baseLat:48.85,baseLon:2.35},settings:{weekDate:shown,days:WORK},plan:{},calendarEvents:[]};
  const ctx={console,Date:clock(now),JSON,Math,Object,Array,String,Number,Set,Map,RegExp,Promise,document:doc,state,addEventListener(){},setTimeout(){},CustomEvent:class{},storeRunnerHasValidBase:()=>true,storeRunnerPreparePlanningOrigin:async()=>{trace.push('gps-start');const result=await location(state);trace.push('gps-done');return result},StoreRunnerTerrainPlanningV1:{resolveSnailStart:(...args)=>{trace.push('time');return terrain.resolveSnailStart(...args)},generateThreeWeekSnail:async options=>{trace.push('engine');return {totalVisits:1,uniqueStores:1,options,base:clone(state.profile)}}}};
  ctx.window=ctx;vm.runInNewContext(read('planning-generation-controller.js'),ctx);return {ctx,trace,button};
}
const results=[];
async function test(name,fn){try{await fn();results.push({name,ok:true})}catch(e){results.push({name,ok:false,error:e.message})}}
(async()=>{
  await test('A — samedi OFF, historique 28/09 : cycle réel 05/10',()=>assert.equal(resolve('2026-10-03','2026-09-28'),'2026-10-05'));
  await test('B — 12/10 consulté sans choix futur : cycle réel 05/10',()=>assert.equal(resolve('2026-10-03','2026-10-12'),'2026-10-05'));
  await test('C — mercredi réel : première semaine courante, jours restants',()=>assert.equal(resolve('2026-10-07','2026-09-28'),'2026-10-05'));
  await test('choix passé explicite ne fait jamais reculer le cycle',()=>assert.equal(resolve('2026-10-03','2026-09-28','2026-09-14',true),'2026-10-05'));
  await test('choix futur explicite peut repousser le cycle',()=>assert.equal(resolve('2026-10-03','2026-09-28','2026-10-19',true),'2026-10-19'));
  await test('samedi actif reste exploitable dans la semaine réelle',()=>assert.equal(resolve('2026-10-03','2026-09-28',null,false,{settings:{days:DAYS}}),'2026-09-28'));
  await test('reste de semaine bloqué Agenda : lundi travaillé suivant',()=>assert.equal(resolve('2026-10-07','2026-09-28',null,false,{calendarEvents:['2026-10-07','2026-10-08','2026-10-09'].map(date=>({date,title:'Formation'}))}),'2026-10-12'));
  await test('génération réelle samedi ignore le passé même demandé directement',async()=>{const t=runtime('2026-10-03');const r=await t.ctx.StoreRunnerTerrainPlanningV1.generateThreeWeekSnail({start:'2026-09-28'});assert.deepEqual(Array.from(r.weeks,w=>w.weekKey),['2026-10-05','2026-10-12','2026-10-19']);assert.equal(t.ctx.state.settings.weekDate,'2026-10-05')});
  await test('C — mercredi aucun nouveau lundi/mardi ; visites passées conservées',async()=>{const t=runtime('2026-10-07',{shown:'2026-10-05'});t.ctx.state.plan.Lundi=[t.stores[0]];t.ctx.state.plan.Mardi=[t.stores[1]];const r=await t.ctx.StoreRunnerTerrainPlanningV1.generateThreeWeekSnail({start:'2026-10-05'});assert.deepEqual(Array.from(r.weeks[0].plan.Lundi,s=>s.id),['s0']);assert.deepEqual(Array.from(r.weeks[0].plan.Mardi,s=>s.id),['s1']);assert.ok(r.weeks[0].plan.Mercredi.length>0);assert.deepEqual(Array.from(r.weeks[0].frozenDays),['Lundi','Mardi'])});
  await test('refus conserve ensemble plan/date/inputs/archive précédents',async()=>{const t=runtime('2026-10-03',{locks:{s0:{week:'2026-10-05',day:'Samedi'}}}),before=JSON.stringify(t.ctx.state),controls=JSON.stringify(t.f);await assert.rejects(()=>t.ctx.StoreRunnerTerrainPlanningV1.generateThreeWeekSnail({start:'2026-10-05'}));assert.ok(JSON.stringify(t.ctx.state)===before,'le refus a modifié state avant application');assert.ok(JSON.stringify(t.f)===controls,'le refus a modifié les dates des champs');assert.equal(t.storage.getItem('chef_sector_plan_archive_v1'),null)});
  await test('Agenda en préparation ne publie pas S1/S2/S3 avant application',async()=>{const t=runtime('2026-10-03'),seen=[];let release;t.ctx.syncGoogleCalendar=()=>{seen.push(t.ctx.state.settings.weekDate);return new Promise(r=>{release=()=>r({ok:true})})};const running=t.ctx.StoreRunnerTerrainPlanningV1.generateThreeWeekSnail({start:'2026-10-05'});await Promise.resolve();assert.equal(t.ctx.state.settings.weekDate,'2026-09-28');assert.equal(t.f.weekDate.value,'2026-09-28');release();await running;assert.deepEqual(seen,['2026-09-28'])});
  await test('contrôleur : temps réel puis GPS attendu puis moteur avec origine fraîche',async()=>{let release;const t=controller('2026-10-03','2026-09-28',state=>new Promise(r=>{release=()=>{state.profile.baseLat=45.75;state.profile.baseLon=4.85;r({ok:true,source:'gps'})}}));const running=t.ctx.storeRunnerGenerateThreeWeeks();await Promise.resolve();assert.deepEqual(t.trace,['time','gps-start']);assert.equal(t.button.disabled,true);release();const out=await running;assert.equal(out.ok,true);assert.deepEqual(t.trace,['time','gps-start','gps-done','engine']);assert.equal(out.result.options.start,'2026-10-05');assert.equal(out.result.options.today,'2026-10-03');assert.equal(out.result.base.baseLat,45.75)});
  await test('contrôleur : origine refusée bloque avant moteur',async()=>{const t=controller('2026-10-03','2026-10-12',async()=>({ok:false,error:'Localisation indisponible'}));const out=await t.ctx.storeRunnerGenerateThreeWeeks();assert.equal(out.ok,false);assert.equal(out.error,'Localisation indisponible');assert.ok(!t.trace.includes('engine'));assert.equal(t.button.disabled,false)});
  await test('B — contrôle principal 12/10 consulté reste au 05/10',async()=>{const t=controller('2026-10-03','2026-10-12',async()=>({ok:true,source:'saved_base',message:'Base utilisateur enregistrée.'}));const out=await t.ctx.storeRunnerGenerateThreeWeeks();assert.equal(out.start,'2026-10-05');assert.equal(out.origin,'saved_base')});
  await test('absence propriétaire GPS bloque proprement, aucun fallback silencieux',async()=>{const t=controller('2026-10-03','2026-09-28',async()=>({ok:true,source:'gps'}));delete t.ctx.storeRunnerPreparePlanningOrigin;const out=await t.ctx.storeRunnerGenerateThreeWeeks();assert.equal(out.ok,false);assert.match(out.error,/localisation n’est pas encore chargée/);assert.ok(!t.trace.includes('engine'))});
  for(const r of results)console.log((r.ok?'PASS ':'FAIL ')+r.name+(r.ok?'':' — '+r.error));const failed=results.filter(r=>!r.ok);console.log(results.length+' scénarios · '+failed.length+' échec(s)');if(failed.length)process.exitCode=1;
})();
