const assert=require('node:assert/strict'),{test}=require('node:test'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
const M=require('../store-runner-visit-model.js'),R=require('../reliability-core.js'),S=require('../store-runner-visit-store.js');
const code=fs.readFileSync(require.resolve('../runner-report-ai-auto-v2771.js'),'utf8');
const canonical=x=>JSON.stringify(x,(k,v)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.keys(v).sort().map(key=>[key,v[key]])):v);
class DB{constructor(){this.map=new Map();this.disk=new Map();this.atomic=true;this.fail=false}getItem(k){return this.map.get(k)??null}setItem(k,v){this.map.set(k,String(v))}removeItem(k){this.map.delete(k)}async flush(){if(this.fail)throw Error('IndexedDB interrompu');this.disk=new Map(this.map)}restart(){const d=new DB();d.map=new Map(this.disk);d.disk=new Map(this.disk);return d}}
function fixture(){const s={schemaVersion:5,stores:[{id:'c',enseigne:'Schmidt',ville:'Ville-Test',channel:'cuisiniste'}],visits:{},notes:{},plan:{},profile:{},settings:{}},id=M.start(s,'c');M.editReport(s,id,'shared','context','un américain Samsung RS68A882 présent en showroom à 749 €.\nRevoir la gérante vendredi.');M.editVisit(s,id,'conclusion',null,'Visite cuisine');M.complete(s,id,'2026-10-07');return{s,id}}
function result(job){return{version:1,reports:job.source.reports.map(r=>({reportType:r.reportType,items:[{section:'showroom',source:r.entries[0].source,quote:r.entries[0].text,text:r.entries[0].text}]}))}}
function harness(initial=fixture(),disk=new DB(),server={jobs:new Map(),calls:0,posts:0,gets:0}){
 let state=M.clone(initial.s),clock=Date.now();disk.setItem(R.keys.MAIN,JSON.stringify(state));disk.disk=new Map(disk.map);
 const sandbox={StoreRunnerVisitModel:M,crypto:crypto.webcrypto,AbortController,URL,Uint8Array,console,navigator:{onLine:true},aiConfig:{gateway:'/api/ai'},Date:class extends Date{static now(){return clock}},setTimeout:()=>1,clearTimeout:()=>{},callAIGateway:()=>{throw Error('Interdit : provider côté téléphone')}};
 Object.defineProperty(sandbox,'state',{get:()=>state,set:x=>{state=x}});
 const session=S.create({model:M,reliability:R,db:disk,getState:()=>state,setState:s=>{state=s},onStatus:()=>{}});
 const guard=j=>({generation:j.generation,completedDate:j.completedDate,sourceSignature:j.sourceSignature});
 sandbox.StoreRunnerVisits={persistReportJob:async(id,expected,patch)=>{let ok=false;await session.edit(s=>{if(s.businessV2.visits.some(v=>v.id===id))ok=M.updateReportJob(s,id,expected,patch)});return ok},applyReportResult:async(id,expected,data,reports,memory)=>{let ok=false;await session.edit(s=>{if(s.businessV2.visits.some(v=>v.id===id))ok=M.applyProfessionalReport(s,id,expected,data,reports,memory)});return ok},ensureReportIntent:async id=>{let ok=false;await session.edit(s=>{const v=s.businessV2.visits.find(v=>v.id===id);if(v&&v.status==='completed'&&!v.reportJob){M.createReportJob(s,id);ok=true}});return ok}};
 sandbox.StoreRunnerReportRenderer={sourceSignature:async source=>'sha256-'+crypto.createHash('sha256').update(canonical(source)).digest('hex'),validate:(r,p)=>{if(!r||r.version!==1||!r.reports||!r.reports.length)throw Error('JSON invalide');return r},render:r=>r.items.map(x=>x.text).join('\n'),memory:(r,p)=>({version:1,sourceSignature:p.sourceSignature,items:r.reports.flatMap(rep=>rep.items.map(x=>({kind:'product',text:x.quote,source:x.source,family:'',status:'recorded'})))})};
 sandbox.fetch=async(url,opt)=>{
  let j;if(opt.method==='POST'){
   server.posts++;const body=JSON.parse(opt.body),saved=JSON.parse(disk.disk.get(R.keys.MAIN)).businessV2.visits.find(v=>v.id===body.visitId).reportJob;
   assert.equal(saved.sourceSignature,body.sourceSignature,'signature sur disque avant le réseau');assert.equal(saved.accessToken,body.accessToken,'capacité sur disque avant le réseau');
   const key=crypto.createHash('sha256').update(canonical([body.visitId,body.storeId,body.completedDate,body.sourceSignature,body.generation,body.accessToken])).digest('hex');
   if(!server.jobs.has(key)){server.calls++;server.jobs.set(key,{...body,protocolVersion:1,jobId:key,status:'pending'})}j=server.jobs.get(key);
  }else{server.gets++;j=server.jobs.get(url.split('/').at(-1));assert.equal(opt.headers['X-Report-Capability'],j.accessToken)}
  if(server.dropResponse){server.dropResponse=false;throw Error('Réseau disparu après acceptation')}
  return{ok:true,status:200,json:async()=>M.clone(j)};
 };
 const context=vm.createContext(sandbox);vm.runInContext(code,context);
 return{api:sandbox.StoreRunnerReportAIAutoV2771,sandbox,disk,server,session,guard,get s(){return state},get v(){return M.getVisit(state,initial.id)},id:initial.id,advance:ms=>{clock+=ms},finish:()=>{for(const j of server.jobs.values()){j.status='done';j.result=result(j)}}};
}

test('clôture locale crée une outbox et un cliché source sans réseau ni mutation IA',()=>{const {s,id}=fixture(),v=M.getVisit(s,id);assert.equal(v.status,'completed');assert.equal(v.reportJob.status,'pending');assert.equal(v.runnerMemory.version,1);assert.equal(v.reportJob.source.reports.length,1);assert.equal(v.reportJob.source.reports[0].reportType,'cuisiniste');const before=JSON.stringify(v.report);M.complete(s,id,'2026-10-07');assert.equal(JSON.stringify(v.report),before);assert.equal(v.reportJob.generation,0)});
test('produits production BRUN/BLANC sont normalisés ; contexte seul cuisine reste un rapport unique',()=>{for(const family of ['Brun','Blanc']){const s={stores:[{id:'r',enseigne:'Darty',ville:'Test',products:[family]}],visits:{}},id=M.start(s,'r');M.editReport(s,id,'shared','context','Premier contact magasin');M.editVisit(s,id,'conclusion',null,'Premier contact magasin');M.complete(s,id,'2026-10-08');const source=M.sourceForReportJob(M.getVisit(s,id));assert.deepEqual(source.reports.map(r=>r.reportType),[family.toLowerCase()]);assert.equal(source.reports[0].entries.length,1,'la conclusion copiée ne duplique pas les notes');}const f=fixture();assert.deepEqual(M.reportTypes(f.s,M.getVisit(f.s,f.id)),['cuisiniste'])});
test('signature et capacité sont durables avant POST ; retour concurrent crée un seul travail payant',async()=>{const h=harness();await Promise.all([h.api.reconcileVisit(h.id),h.api.reconcileVisit(h.id),h.api.scan()]);assert.equal(h.server.posts,1);assert.equal(h.server.calls,1);assert.equal(h.v.reportJob.status,'pending');assert.match(h.v.reportJob.sourceSignature,/^sha256-[a-f0-9]{64}$/)});
test('fermeture puis reprise disque interroge le résultat serveur, sans nouveau POST ni provider client',async()=>{const h=harness();await h.api.reconcileVisit(h.id);h.finish();const saved=R.load(h.disk.restart()),restart=harness({s:saved,id:h.id},h.disk.restart(),h.server);restart.advance(4000);await restart.api.reconcileVisit(h.id);assert.equal(restart.server.posts,1);assert.equal(restart.server.gets,1);assert.equal(restart.server.calls,1);assert.equal(restart.v.reportJob.status,'done');assert.match(M.professionalReportOf(restart.v,'cuisiniste').text,/RS68A882.*749 €/);assert.equal(restart.v.runnerAI.status,'done')});
test('acceptation serveur avec réponse réseau perdue reprend exactement le même job',async()=>{const h=harness();h.server.dropResponse=true;await h.api.reconcileVisit(h.id);assert.equal(h.v.reportJob.jobId,'');h.advance(60001);await h.api.reconcileVisit(h.id);assert.equal(h.server.posts,2);assert.equal(h.server.calls,1);assert.notEqual(h.v.reportJob.jobId,'')});
test('hors ligne conserve clôture, carnet et outbox puis reprend online',async()=>{const h=harness(),raw=JSON.stringify(h.v.report);h.sandbox.navigator.onLine=false;assert.equal(await h.api.reconcileVisit(h.id),false);assert.equal(h.server.posts,0);assert.equal(h.v.status,'completed');assert.equal(JSON.stringify(h.v.report),raw);h.sandbox.navigator.onLine=true;await h.api.reconcileVisit(h.id);assert.equal(h.server.calls,1)});
test('un provider failed conserve le compte rendu précédent et le fallback Runner',async()=>{const h=harness();await h.api.reconcileVisit(h.id);h.finish();h.advance(4000);await h.api.reconcileVisit(h.id);const previous=JSON.stringify(h.v.professionalReport);await h.session.edit(s=>M.createReportJob(s,h.id,true));await h.api.reconcileVisit(h.id);const j=[...h.server.jobs.values()].at(-1);j.status='failed';j.error={code:'timeout',message:'IA indisponible'};h.advance(4000);await h.api.reconcileVisit(h.id);assert.equal(h.v.status,'completed');assert.equal(h.v.reportJob.status,'failed');assert.equal(JSON.stringify(h.v.professionalReport),previous);assert(h.v.runnerMemory.items.length>0)});
for(const invalid of [undefined,'',null,{version:1,reports:[]}])test('réponse vide ou tronquée refusée sans effacer les notes : '+JSON.stringify(invalid),async()=>{const h=harness();await h.api.reconcileVisit(h.id);const j=[...h.server.jobs.values()][0];j.status='done';j.result=invalid;h.advance(4000);await h.api.reconcileVisit(h.id);assert.equal(h.v.reportJob.status,'failed');assert.equal(h.v.professionalReport,undefined);assert.match(h.v.report.shared.context,/749 €/);assert.equal(h.v.status,'completed')});
test('édition finale pendant une tâche invalide son application et ne touche jamais aux notes',async()=>{const h=harness();await h.api.reconcileVisit(h.id);const raw=JSON.stringify(h.v.report);await h.session.edit(s=>M.editProfessionalReport(s,h.id,'cuisiniste','Compte rendu relu et modifié'));h.finish();h.advance(4000);await h.api.reconcileVisit(h.id);assert.equal(M.professionalReportOf(h.v,'cuisiniste').text,'Compte rendu relu et modifié');assert.equal(h.v.reportJob.obsolete,true);assert.equal(JSON.stringify(h.v.report),raw);assert.deepEqual(Array.from(h.api.pendingIds()),[])});
test('réouverture/reclôture : ancien résultat rejeté, sources précédentes intactes et génération distincte',async()=>{const h=harness();await h.api.reconcileVisit(h.id);const old=M.clone(h.v.reportJob),expected=h.guard(old);await h.session.edit(s=>{const v=M.getVisit(s,h.id);v.status='draft';v.completedDate=null;v.completedAt=null;v.reportJob.obsolete=true;M.editReport(s,h.id,'shared','context','RS68A882 à 899 € ; revoir la gérante.');M.complete(s,h.id,'2026-10-07')});assert.equal(h.v.reportJob.generation,1);assert.match(h.v.reportSourceHistory[0].source.reports[0].entries[0].text,/749 €/);assert.equal(M.reportJobGuard(h.v,expected),false);assert.notEqual(h.v.reportJob.localSourceSignature,old.localSourceSignature);assert.equal(h.v.status,'completed')});
test('suppression pendant une tâche rend la réponse sans cible et sans mémoire orpheline',async()=>{const h=harness();await h.api.reconcileVisit(h.id);await h.session.edit(s=>M.removeVisit(s,h.id));h.finish();h.advance(4000);assert.equal(await h.api.reconcileVisit(h.id),false);assert.equal(h.s.businessV2.visits.length,0);assert.deepEqual(M.reportMemoryFor(h.s,'c').items,[])});
test('régénérations rapprochées réutilisent pending/processing ; failed ou done crée une génération',()=>{const {s,id}=fixture(),j=M.getVisit(s,id).reportJob;M.createReportJob(s,id,true);assert.equal(M.getVisit(s,id).reportJob,j);j.status='processing';M.createReportJob(s,id,true);assert.equal(M.getVisit(s,id).reportJob,j);j.status='failed';M.createReportJob(s,id,true);assert.equal(M.getVisit(s,id).reportJob.generation,1)});
test('sauvegarde scellée conserve final, job et sources ; nouveau schéma facultatif vérifié',async()=>{const h=harness();await h.api.reconcileVisit(h.id);h.finish();h.advance(4000);await h.api.reconcileVisit(h.id);const sealed=R.seal(R.capture(h.s,h.disk)),decoded=R.decode(JSON.stringify(sealed),h.s);assert.deepEqual(decoded.state.businessV2.visits,h.s.businessV2.visits);const corrupt=M.clone(h.s);corrupt.businessV2.visits[0].reportJob.accessToken='incorrect';assert.throws(()=>M.validate(corrupt),/Tâche/);const old=M.clone(h.s);delete old.businessV2.visits[0].reportJob;delete old.businessV2.visits[0].professionalReport;assert.doesNotThrow(()=>M.validate(old))});
test('ancien pending V277.1 migre via le même writer puis poste un seul job serveur',async()=>{const f=fixture(),v=M.getVisit(f.s,f.id);delete v.reportJob;const h=harness(f);await h.api.reconcileVisit(h.id);assert.equal(h.server.calls,1);assert.equal(h.v.reportJob.version,1)});
test('échec IndexedDB avant POST interdit tout travail distant et garde le brouillon durable',async()=>{const h=harness();h.disk.fail=true;assert.equal(await h.api.reconcileVisit(h.id),false);assert.equal(h.server.calls,0);assert.equal(M.getVisit(R.load(h.disk.restart()),h.id).reportJob.sourceSignature,'')});
