const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const html = fs.readFileSync('src/chef-secteur.html', 'utf8');
const channel = vm.runInNewContext('(' + html.match(/function storeChannel\(store\)\{[^\n]+/)[0] + ')');
const old = {enseigne:'Darty', type:'Gros'};
assert.equal(channel(old), 'retail');
assert.equal(old.type, 'Gros');
for (const enseigne of ['Schmidt', ' SCHMIDT ', 'Cuisinella']) assert.equal(channel({enseigne}), 'cuisiniste');
assert.equal(channel({enseigne:'Schmidt',channel:'retail'}), 'retail');
assert.equal(channel({enseigne:'Darty',channel:'cuisiniste'}), 'cuisiniste');
assert.equal(channel({enseigne:'Schmidt',channel:'unknown'}), 'cuisiniste');
const ai = html.match(/function addAIParsedStores\(\)\{[^\n]+/)[0];
assert.doesNotMatch(ai, /state\.stores|\.push\(|save\(/);
assert.match(ai, /openStoreCreation\(aiParsedStores\)/);
assert.match(html, /if\(!id\)\{openStoreCreation\(\);return\}/);
assert.match(html, /RegionStores\.commit\(\[draft\]\)/);
assert.match(html, /RegionStores\.enrich\(draft\)/);
assert.match(html, /id="fLat" type="hidden"/);
assert.match(html, /id="fLon" type="hidden"/);
const form=html.match(/<dialog id="createStoreDlg"[\s\S]*?<\/dialog>/)[0];
assert.doesNotMatch(form, /latitude|longitude|GPS|sourceName|type="number"/i);
console.log('PASS: historical type preserved, channel precedence/fallback, AI and local creation routed through shared geocoding/confirmation, hidden coordinates.');
