const fs = require('fs');
const assert = require('assert');

const index = fs.readFileSync('index.html','utf8');
const sw = fs.readFileSync('sw.js','utf8');
const version = JSON.parse(fs.readFileSync('version.json','utf8'));
const source = fs.readFileSync('terrain-planning-v1.js','utf8');
const capacity = fs.readFileSync('daily-capacity.js','utf8');
const geography = fs.readFileSync('v182-fixes.js','utf8');
const routeOptimizer = fs.readFileSync('planning-route-optimizer-v251.js','utf8');
const planningPro = fs.readFileSync('planning-pro-plus.js','utf8');

assert(index.includes("'./range-planner-v2.js','./store-opening-hours.js','./boulanger-default-hours.js','./store-photos.js','./terrain-planning-v1.js','./working-hours-end.js'"), 'les horaires enseigne et les photos doivent charger avant le module terrain');
assert(sw.includes('"./terrain-planning-v1.js"'), 'le module terrain doit être disponible hors ligne');
assert.match(String(version.displayVersion||''), /^\d+$/, 'displayVersion doit rester un numéro de version publié');
assert.match(String(version.latestBuild||''), /^\d{8}-[a-z0-9-]+$/i, 'latestBuild doit rester un identifiant de build publié');
assert(index.includes("const BUILD_REV='"+version.latestBuild+"'"), 'index.html doit utiliser le build déclaré par version.json');
assert(sw.includes('const BUILD_REV = "'+version.latestBuild+'"'), 'sw.js doit utiliser le build déclaré par version.json');
assert(index.includes("scriptTag('./store-runner-visits.js')+scriptTag('./store-runner-opportunities.js')"),'Opportunity doit charger après le propriétaire Visit');
assert(sw.includes('"./store-runner-opportunities.js"'),'Opportunity doit fonctionner hors ligne');
assert(index.includes("'./planning-generation-controller.js','./planning-cascade-v181.js','./calendar-enhancements.js'"), 'la cascade doit prendre la main juste après le contrôleur planning');
assert(sw.includes('"./planning-cascade-v181.js"'), 'le recalcul en cascade doit rester disponible hors ligne');
assert(index.includes("'./sector-pilotage.js','./v182-fixes.js','./planning-route-optimizer-v251.js','./auto-planning-fix.js'"), 'V251 doit s’installer après la géographie V185 et avant la finalisation runtime');
assert(sw.includes('"./planning-route-optimizer-v251.js"'), 'l’optimiseur routier V251 doit rester disponible hors ligne');
assert(routeOptimizer.includes("source!=='snail-geo-v185'&&source!=='generateWeek'"), 'V251 ne doit se déclencher qu’après une génération explicite finalisée');
assert(!routeOptimizer.includes('window.generateWeek='), 'V251 ne doit pas reprendre le propriétaire generateWeek');
assert(!routeOptimizer.includes('root.generateWeek='), 'V251 ne doit pas reprendre le propriétaire generateWeek');
assert(!index.includes("'./priority-campaign-v187.js'"), 'la campagne échue V187 ne doit plus être chargée');
assert(sw.includes('"./v182-fixes.js"'), 'les correctifs V182/V185 doivent rester disponibles hors ligne');
assert(!sw.includes('"./priority-campaign-v187.js"'), 'la campagne échue V187 ne doit plus être précachée');
assert(sw.includes('"./store-opening-hours.js"'), 'horaires disponibles hors ligne');
assert(sw.includes('"./boulanger-default-hours.js"'), 'défauts Boulanger/Darty disponibles hors ligne');
assert(sw.includes('"./store-photos.js"'), 'mémoire photo magasin disponible hors ligne');
assert(sw.includes('"./planning-manual-visits.js"'), 'les gestes manuels du planning doivent être disponibles hors ligne');
assert(index.includes("'./period-day-slider.js','./planning-manual-visits.js','./workdays-enforcer.js'"), 'le module manuel doit charger après le slider de jours');
assert(index.includes("'./daily-capacity.js','./planning-pro-plus.js'"), 'les réglages de capacité doivent rester dans le runtime PWA existant');
assert(capacity.includes("target.addEventListener('input'"), 'l’objectif hebdomadaire doit être persisté dès la saisie');
assert(capacity.includes('state.settings.target='), 'le module capacité doit conserver la valeur hebdomadaire choisie');
assert(!index.includes('__v184PlanningCapacity'), 'V184 ne doit plus envelopper le générateur terrain 3 semaines');
assert(!index.includes('function patchThreeWeeks()'), 'le patch legacy B2 doit rester supprimé');
assert(geography.includes('window.__storeRunnerPlanningGenerationActive=true'), 'V185 doit conserver le drapeau de génération utilisé par Agenda');
assert(geography.includes('patchThreeWeekGeography'), 'V185 doit rester interposé avant le moteur terrain');
assert(!index.includes('terrainSnailBtn'), 'V184 ne doit plus réparer le bouton terrain retiré');
assert(!index.includes('window.StoreRunnerV184='), 'V184 ne doit plus exposer une API de diagnostic sans consommateur');
assert(!planningPro.includes("getElementById('planningProPlus')"), 'planning-pro-plus ne doit plus nettoyer un ancien conteneur jamais créé');
assert(index.includes("'./performance-ui-v190.js','./assistant-performance-context-v192.js','./visit-mobile-ux-v215.js','./visit-mobile-tabs-v216.js','./update-manager.js'"),'le pont performance V192 puis les couches UX visite V215/V216 doivent charger avant le gestionnaire de mise à jour');
assert(sw.includes('"./assistant-performance-context-v192.js"'),'le pont performance V192 doit rester disponible hors ligne');
assert(sw.includes('"./visit-mobile-ux-v215.js"'),'l’UX visite V215 doit rester disponible hors ligne');
assert(sw.includes('"./visit-mobile-tabs-v216.js"'),'les onglets visite V216 doivent rester disponibles hors ligne');
assert(sw.includes('"./cuisiniste-contracts-v193.js"'),'le moteur contrats expo V193 doit rester disponible hors ligne');
assert(!source.includes('window.generateWeek='), 'le module terrain ne doit pas reprendre generateWeek');
assert(!source.includes('root.generateWeek='), 'le module terrain ne doit pas reprendre generateWeek');
assert(!source.includes('window.generatePlanningRange='), 'le générateur de période stable doit rester propriétaire');
assert(source.includes('root.StoreRunnerTerrainPlanningV1=api'));
console.log('terrain-planning-runtime: OK');
