const fs = require('fs');
const assert = require('assert');

const index = fs.readFileSync('index.html','utf8');
const sw = fs.readFileSync('sw.js','utf8');
const version = JSON.parse(fs.readFileSync('version.json','utf8'));
const source = fs.readFileSync('terrain-planning-v1.js','utf8');
const capacity = fs.readFileSync('daily-capacity.js','utf8');

assert(index.includes("'./range-planner-v2.js','./store-opening-hours.js','./boulanger-default-hours.js','./store-photos.js','./terrain-planning-v1.js','./working-hours-end.js'"), 'les horaires enseigne et les photos doivent charger avant le module terrain');
assert(sw.includes('"./terrain-planning-v1.js"'), 'le module terrain doit être disponible hors ligne');
assert.strictEqual(version.displayVersion, '197');
assert.strictEqual(version.latestBuild, '20260917-anonresidus197');
assert(index.includes("const BUILD_REV='20260917-anonresidus197'"));
assert(sw.includes('const BUILD_REV = "20260917-anonresidus197"'));
assert(index.includes("'./planning-generation-controller.js','./planning-cascade-v181.js','./calendar-enhancements.js'"), 'la cascade doit prendre la main juste après le contrôleur planning');
assert(sw.includes('"./planning-cascade-v181.js"'), 'le recalcul en cascade doit rester disponible hors ligne');
assert(index.includes("'./sector-pilotage.js','./v182-fixes.js','./priority-campaign-v187.js','./auto-planning-fix.js'"), 'le moteur de priorités V188 doit charger après les règles géographiques et avant la finalisation runtime');
assert(sw.includes('"./v182-fixes.js"'), 'les correctifs V182/V185 doivent rester disponibles hors ligne');
assert(sw.includes('"./priority-campaign-v187.js"'), 'le moteur de priorités V188 doit rester disponible hors ligne');
assert(sw.includes('"./store-opening-hours.js"'), 'horaires disponibles hors ligne');
assert(sw.includes('"./boulanger-default-hours.js"'), 'défauts Boulanger/Darty disponibles hors ligne');
assert(sw.includes('"./store-photos.js"'), 'mémoire photo magasin disponible hors ligne');
assert(sw.includes('"./planning-manual-visits.js"'), 'les gestes manuels du planning doivent être disponibles hors ligne');
assert(index.includes("'./period-day-slider.js','./planning-manual-visits.js','./workdays-enforcer.js'"), 'le module manuel doit charger après le slider de jours');
assert(index.includes("'./daily-capacity.js','./planning-pro-plus.js'"), 'les réglages de capacité doivent rester dans le runtime PWA existant');
assert(capacity.includes("target.addEventListener('input'"), 'l’objectif hebdomadaire doit être persisté dès la saisie');
assert(capacity.includes('state.settings.target='), 'le module capacité doit conserver la valeur hebdomadaire choisie');
assert(index.includes('window.__storeRunnerPlanningGenerationActive=true'), 'V184 doit activer la capacité planning pendant la génération 3 semaines');
assert(index.includes('api.generateThreeWeekSnail=wrapped'), 'V184 doit envelopper le générateur terrain 3 semaines');
assert(index.includes('terrainSnailBtn')&&index.includes('api.generateThreeWeekSnail()'), 'le bouton terrain existant doit être rebranché vers le générateur corrigé');
assert(index.includes("'./performance-ui-v190.js','./assistant-performance-context-v192.js','./update-manager.js'"),'le pont performance V192 doit charger après la couche performance et avant le gestionnaire de mise à jour');
assert(sw.includes('"./assistant-performance-context-v192.js"'),'le pont performance V192 doit rester disponible hors ligne');
assert(sw.includes('"./cuisiniste-contracts-v193.js"'),'le moteur contrats expo V193 doit rester disponible hors ligne');
assert(!source.includes('window.generateWeek='), 'le module terrain ne doit pas reprendre generateWeek');
assert(!source.includes('root.generateWeek='), 'le module terrain ne doit pas reprendre generateWeek');
assert(!source.includes('window.generatePlanningRange='), 'le générateur de période stable doit rester propriétaire');
assert(source.includes('root.StoreRunnerTerrainPlanningV1=api'));
console.log('terrain-planning-runtime: OK');
