const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const M=require('../store-runner-visit-model.js'),R=require('../reliability-core.js');
const original={schemaVersion:5,profile:{baseName:'Lyon'},settings:{days:['Lundi']},stores:[{id:'x',enseigne:'Darty',ville:'Lyon'},{id:'y',enseigne:'Fnac',ville:'Lyon'}],notes:{x:'Conserver'},visits:{x:{history:['2026-09-01'],lastVisit:'2026-09-01'}},plan:{Lundi:[{id:'x'}]},appointments:[{id:'rdv',storeId:'x',date:'2026-09-14',time:'10:00'}],calendarEvents:[]};
const s=M.clone(original),id=M.start(s,'x');assert.equal(M.start(s,'x'),id);assert.notEqual(M.start(s,'y'),id);
M.editVisit(s,id,'preparation','mainGoal','Revoir les ruptures');M.editVisit(s,id,'check',0,true);M.editVisit(s,id,'step',null,2);
for(const p of Object.keys(M.SIX_P)){M.edit6P(s,id,p,0,'status','correct');M.edit6P(s,id,p,0,'comment','À vérifier')}
M.edit6P(s,id,'prix',0,'action','Corriger étiquette');M.edit6P(s,id,'prix',0,'owner','Alice');M.edit6P(s,id,'prix',0,'dueDate','2026-09-15');const a=M.actionFrom6P(s,id,'prix',0);assert.equal(M.actionFrom6P(s,id,'prix',0),a);
M.edit6P(s,id,'prix',0,'owner','Bob');assert.equal(s.businessV2.actions[0].owner,'Bob');M.editAction(s,a,'owner','Chloé');M.editAction(s,a,'dueDate','2026-09-16');assert.equal(M.getVisit(s,id).sixP.prix[0].owner,'Chloé');assert.equal(M.getVisit(s,id).sixP.prix[0].dueDate,'2026-09-16');M.edit6P(s,id,'prix',0,'dueDate','2026-09-17');assert.equal(s.businessV2.actions[0].dueDate,'2026-09-17');
const anomaly=M.addAnomaly(s,id);M.editAnomaly(s,id,anomaly,'Démo éteinte');const aa=M.actionFromAnomaly(s,id,anomaly);assert.equal(M.actionFromAnomaly(s,id,anomaly),aa);const second=M.addAnomaly(s,id);M.editAnomaly(s,id,second,'Autre démo éteinte');assert.notEqual(M.actionFromAnomaly(s,id,second),aa);assert.equal(s.businessV2.actions.length,3);
assert.throws(()=>M.complete(s,id,'2026-09-10'),/conclusion/);M.editVisit(s,id,'conclusion',null,'Priorités convenues');M.complete(s,id,'2026-09-10');M.complete(s,id,'2026-09-10');assert.deepEqual(s.visits.x.history,['2026-09-01','2026-09-10']);assert.equal(s.businessV2.actions.length,3);assert.throws(()=>M.editVisit(s,id,'step',null,0),/terminée/);
M.editAction(s,a,'owner','David');assert.equal(M.getVisit(s,id).sixP.prix[0].owner,'David');M.editAction(s,a,'status','done');assert(s.businessV2.actions[0].completedAt);M.editAction(s,a,'status','open');assert.equal(s.businessV2.actions[0].completedAt,null);
const sameDay=M.start(s,'x');assert.notEqual(sameDay,id);M.editVisit(s,sameDay,'conclusion',null,'Second passage');M.complete(s,sameDay,'2026-09-10');assert.equal(s.visits.x.history.length,2);
for(const key of ['profile','settings','notes','plan','appointments','calendarEvents'])assert.deepEqual(s[key],original[key]);R.validateState(s);
const bad=M.clone(s);bad.businessV2.actions[0].owner='désynchronisé';assert.throws(()=>R.validateState(bad),/désynchronisé/);assert.throws(()=>M.editAction(s,a,'dueDate','2026-02-30'));const duplicate=M.clone(s);duplicate.businessV2.actions.push(M.clone(duplicate.businessV2.actions[0]));assert.throws(()=>R.validateState(duplicate));
class DB{constructor(){this.map=new Map()}getItem(k){return this.map.get(k)??null}setItem(k,v){this.map.set(k,String(v))}removeItem(k){this.map.delete(k)}}
const db=new DB();global.state=s;global.__chefStorage=db;R.save(s);const bundle=R.capture();assert.deepEqual(bundle.state,s);const clean=new DB();R.persist(R.decode(JSON.stringify(bundle),original),clean);assert.deepEqual(R.load(clean),s);assert.equal(M.start(R.load(clean),'y'),s.businessV2.visits.find(v=>v.storeId==='y').id);assert.deepEqual(R.restore(bundle),s);assert.equal(R.decode(JSON.stringify(original),s).state.businessV2,undefined);
const removed=M.clone(s);removed.stores=removed.stores.filter(x=>x.id!=='x');removed.plan={};removed.appointments=[];R.validateState(removed);
const root=path.join(__dirname,'..'),ui=fs.readFileSync(path.join(root,'store-runner-visits.js'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
assert(!/window\.(renderAll|renderWeek|save|openStore|saveStore|saveAppointment|goTab|switchTab)\s*=/.test(ui));assert(!/setInterval\s*\(/.test(ui));for(const asset of ['store-runner-visit-model.js','store-runner-visit-store.js','store-runner-visits.js','store-runner-visits.css'])assert(sw.split('const OPTIONAL_SHELL')[0].includes(asset));
console.log('PASS: Visit/Action workflow, six P, bidirectional owner/date sync, idempotent conversions/closure, history compatibility, V2 backup/restore, interrupted draft, invalid data and module ownership.');
