const assert=require('node:assert/strict'),M=require('../store-runner-visit-model.js'),R=require('../reliability-core.js'),S=require('../store-runner-visit-store.js');
class DB{constructor(){this.map=new Map();this.fail=false;this.hold=null}getItem(k){return this.map.get(k)??null}setItem(k,v){if(this.fail)throw Error('quota');this.map.set(k,String(v))}removeItem(k){this.map.delete(k)}async flush(){if(this.hold)await this.hold;if(this.failFlush)throw Error('IndexedDB interrompu')}}
(async()=>{
 let state={schemaVersion:5,profile:{baseName:'Lyon'},settings:{},stores:[{id:'x',enseigne:'Darty',ville:'Lyon'}],visits:{},notes:{},plan:{}};const db=new DB(),statuses=[];global.state=state;
 const session=S.create({model:M,reliability:R,db,getState:()=>state,setState:s=>{state=s;global.state=s},onStatus:s=>statuses.push(s)});let id;
 await session.edit(s=>{id=M.start(s,'x')});db.fail=true;await assert.rejects(session.edit(s=>M.editVisit(s,id,'preparation','mainGoal','Sauver malgré quota')),/quota|Espace insuffisant/);assert(session.hasPending());assert.equal(M.getVisit(state,id).preparation.mainGoal,'');state.profile.baseName='Paris';db.fail=false;await session.flush();assert.equal(M.getVisit(state,id).preparation.mainGoal,'Sauver malgré quota');assert.equal(state.profile.baseName,'Paris');
 let release;db.hold=new Promise(resolve=>{release=resolve});const saving=session.edit(s=>M.editVisit(s,id,'conclusion',null,'Fin'));assert(session.hasPending());await new Promise(resolve=>setImmediate(resolve));assert.equal(M.getVisit(state,id).conclusion,'');assert.equal(statuses.at(-1),'saving');state.notes.x='Note concurrente';release();await saving;db.hold=null;assert.equal(state.notes.x,'Note concurrente');assert.equal(M.getVisit(state,id).conclusion,'Fin');assert.equal(statuses.at(-1),'saved');
 db.failFlush=true;await assert.rejects(session.edit(s=>M.complete(s,id,'2026-09-10')),/IndexedDB/);assert.equal(M.getVisit(state,id).status,'draft');assert(session.hasPending());state.visits.other={history:['2026-09-09']};db.failFlush=false;await session.flush();assert.equal(M.getVisit(state,id).status,'completed');assert.deepEqual(state.visits.other.history,['2026-09-09']);assert.equal(state.visits.x.history.length,1);assert.deepEqual(R.load(db),state);
 let draft;await session.edit(s=>{draft=M.start(s,'x')});await Promise.all(Array.from({length:12},(_,i)=>session.edit(s=>M.editVisit(s,draft,'preparation','notes',String(i)))));assert.equal(M.getVisit(R.load(db),draft).preparation.notes,'11');assert(!session.hasPending());
 const remote=M.clone(state);remote.businessV2.revision++;db.setItem(R.keys.MAIN,JSON.stringify(remote));await assert.rejects(session.edit(s=>M.editVisit(s,draft,'preparation','notes','Ne pas écraser')),/autre fenêtre/);assert.deepEqual(R.load(db),remote);state=remote;
 db.fail=true;await assert.rejects(session.edit(s=>M.editVisit(s,draft,'preparation','notes','Non enregistré')));session.invalidate();db.fail=false;await session.flush();assert.equal(M.getVisit(state,draft).preparation.notes,'11');
 console.log('PASS: serialized progressive persistence, quota retry, awaited IndexedDB durability/failure, unrelated changes preserved, interrupted closure retry, stale window detection, restoration invalidation.');
})().catch(e=>{console.error(e);process.exitCode=1});
