const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const source=fs.readFileSync(__dirname+'/../visit-counting.js','utf8');
const archive={
  '2026-09-07':{weekMonday:'2026-09-07',plan:{Lundi:[{id:'d1',enseigne:'Darty',ville:'Lyon'}],Mardi:[{id:'c1',enseigne:'Carrefour',ville:'Bron'}],Mercredi:[],Jeudi:[],Vendredi:[],Samedi:[]}},
  '2026-09-14':{weekMonday:'2026-09-14',plan:{Lundi:[{id:'b1',enseigne:'Boulanger',ville:'Saint-Priest'}],Mardi:[{id:'d2',enseigne:'Darty',ville:'Lyon'}],Mercredi:[],Jeudi:[],Vendredi:[],Samedi:[]}}
};
const range={start:'2026-09-07',end:'2026-09-20',weeks:2,totalStores:999,totalVisits:999,uniqueStores:999};
const storageData={chef_sector_plan_archive_v1:JSON.stringify(archive),chef_sector_range_v1:JSON.stringify(range)};
const state={settings:{visitCreditsByBrand:{fnac:3}},stores:[],plan:{Lundi:[{id:'d1',enseigne:'Darty'},{id:'b1',enseigne:'Boulanger'},{id:'c1',enseigne:'Carrefour'}]},visits:{}};
const listeners={};
const localStorage={getItem:key=>Object.prototype.hasOwnProperty.call(storageData,key)?storageData[key]:null,setItem(key,value){storageData[key]=String(value)},removeItem(key){delete storageData[key]}};
const ctx={state,console,Date,Map,Set,RegExp,JSON,Object,Array,String,Number,Math,setTimeout,requestAnimationFrame:fn=>fn(),localStorage,document:{readyState:'loading',addEventListener:(name,fn)=>{listeners[name]=fn},getElementById:()=>null,querySelector:()=>null,querySelectorAll:()=>[]},CustomEvent:class{}};
ctx.window=ctx;vm.runInNewContext(source,ctx);
const V=ctx.StoreVisitCounting;
assert(V,'le module de comptage doit exposer son API de test');
assert.equal(V.credit({enseigne:'Darty'}),2,'Darty doit compter pour deux visites');
assert.equal(V.credit({enseigne:'Boulanger'}),2,'Boulanger doit compter pour deux visites');
assert.equal(V.credit({enseigne:'Carrefour'}),2,'Carrefour doit compter pour deux visites');
assert.equal(V.credit({enseigne:'Fnac'}),3,'une règle ajoutée ultérieurement doit être prise en compte sans modifier le moteur');
assert.equal(V.credit({enseigne:'Leclerc'}),1,'une enseigne non confirmée reste à une visite');
assert.equal(V.planStores(state.plan),3,'les trois arrêts restent trois magasins physiques');
assert.equal(V.planCredits(state.plan),6,'Darty + Boulanger + Carrefour doivent produire six visites comptabilisées');
const candidate={plan:state.plan,weekDate:'2026-09-07',archive,range:{start:'2026-09-07',end:'2026-09-08',weeks:1,totalVisits:2,uniqueStores:2}};
V.normalizeCandidate(candidate);
assert.equal(candidate.storeCount,3,'la proposition hebdomadaire doit conserver le nombre physique de magasins');
assert.equal(candidate.visitCredits,6,'la proposition hebdomadaire doit porter le nombre métier de visites');
assert.equal(candidate.range.totalStores,2,'la période testée contient deux magasins physiques');
assert.equal(candidate.range.totalVisits,4,'la période testée vaut quatre visites métier : Darty x2 + Carrefour x2');
assert.equal(candidate.range.uniqueStores,2);
const reconciled=V.reconcileStoredRangeStats();
assert(reconciled,'le recalcul de période doit retourner les statistiques persistées');
assert.equal(reconciled.totalStores,4,'les quatre passages physiques doivent rester comptés, même si deux IDs représentent le même Darty');
assert.equal(reconciled.totalVisits,8,'les quatre passages Darty/Boulanger/Carrefour doivent conserver leurs huit visites métier pondérées');
assert.equal(reconciled.uniqueStores,3,'deux IDs du même Darty Lyon doivent compter pour un seul magasin physique distinct');
const persistedRange=JSON.parse(storageData.chef_sector_range_v1);
assert.equal(persistedRange.totalStores,4);
assert.equal(persistedRange.totalVisits,8);
assert.equal(persistedRange.uniqueStores,3);
assert.equal(persistedRange.visitCreditRules.carrefour,2,'la période persistée doit conserver la règle Carrefour x2');
const month=V.monthArchiveStats(2026,8);
assert.equal(month.stores,4,'septembre doit contenir quatre passages physiques dans l’archive de test');
assert.equal(month.visits,8,'septembre doit compter huit visites métier');
assert.equal(month.uniqueStores,3,'les statistiques mensuelles doivent dédupliquer un même magasin physique malgré un nouvel ID');
const idOnlyArchive={'2026-09-07':{weekMonday:'2026-09-07',plan:{Lundi:[{id:'u1'},{id:'u2'}],Mardi:[],Mercredi:[],Jeudi:[],Vendredi:[],Samedi:[]}}};
assert.equal(V.archiveStats(idOnlyArchive,'2026-09-07','2026-09-07').uniqueStores,2,'sans enseigne, ville ni adresse, deux IDs différents doivent rester deux magasins distincts');
assert.doesNotMatch(source,/visitMinutes\s*=/,'le double comptage ne doit jamais doubler la durée de visite');
assert.match(source,/darty:2,boulanger:2,carrefour:2/,'Darty, Boulanger et Carrefour doivent être les trois règles par défaut');
assert.match(source,/detail\.reason==='day-store-recenter'/,'le recalcul de période doit rester ciblé sur un recentrage manuel');
assert.doesNotMatch(source,/observe\(document\.body/,'le module de comptage ne doit jamais observer tout document.body');
assert.match(source,/OBSERVED_UI_IDS=\['summary','smartBrief','premiumHomeV2','proMonthBody','storeQuickSheet'\]/,'les zones observées doivent rester explicitement limitées aux vues de comptage utiles');
assert.match(source,/attributeFilter:\['class','aria-hidden','data-sr-start'\]/,'la fiche rapide doit rester rafraîchie quand le magasin affiché change');
console.log('PASS: les visites pondérées restent séparées des arrêts physiques, les statistiques dédupliquent un même magasin physique et le rafraîchissement UI n’observe plus toute l’application.');
